/**
 * OSID-native bot brigade AI — directive-based execution (HoI-style).
 *
 * Brigades read their corps directive (generated by bot_corps_ai.ts) and execute:
 *   - Attack directive targets using combat predictor
 *   - Hold specified positions (chokepoints, enclaves)
 *   - Cover assigned front segments (fill gaps, spread along front)
 *   - Move from interior toward front
 *
 * Faction personality is expressed through CorpsDirective (what targets,
 * what thresholds, what reserve fraction) — brigade execution is faction-agnostic.
 *
 * All decisions operate in OSID space — no dependency on brigade_aor or
 * canonical settlement graphs.
 *
 * Deterministic: sorted iteration, no randomness, no timestamps.
 *
 * This file is the slim orchestrator. Helpers live in submodules:
 *   - bot_brigade_context.ts — brigade location, context, counting
 *   - bot_brigade_movement_ai.ts — movement logic (BFS, column march, interior)
 *   - bot_brigade_targeting.ts — target scoring and combat prediction
 *   - bot_brigade_supply_ethnic.ts — supply state and ethnic composition
 */

import type {
    BrigadePosture,
    CorpsOperation,
    CorpsStance,
    FactionId,
    FormationId,
    FormationState,
    GameState,
    OperationAxis,
} from '../../state/game_state.js';
import { getFormationTier, MIN_ATTACK_PERSONNEL } from '../../state/formation_constants.js';
import { getPoliticalControllerOSID } from '../../state/settlement_control.js';
import { strictCompare } from '../../state/validateGameState.js';
import type { OperationalToCanonicalReverseMap, OsidPopulationMap } from '../../data/operational_data.js';
import {
    predictAllAdjacentTargets,
    buildTerrainCache,
    type PredictedOutcome
} from './combat_predictor.js';
import {
    analyzeFactionGraph,
    type FactionGraphAnalysis,
} from './osid_graph_analysis.js';
import { getEffectiveAttackShare } from './bot_strategy.js';
import {
    buildOsidAdjacency,
    type Osid
} from './osid_adjacency.js';
import { getTacticalAdjacentOsids } from './tactical_adjacency.js';
import { areRbihHrhbAllied, isFriendlyFaction } from '../early_war/alliance_update.js';
import { shouldGrazBlockAttack, isGrazAccordsActive, isEastHerzegovinaPair } from '../local_truces.js';
import type { SupplyStateByOsidReport } from '../../state/supply_state_derivation.js';
import { getEffectiveSupplyState } from '../../state/supply_reserves.js';
import { getSeasonalModifiers } from './seasonal_effects.js';
import { isMultiAxis, getAllAxisBrigades } from './sector_offensive.js';
import { getCorpsStance } from './combat_math.js';
import { findBrigadeOperation } from './corps_operation_helpers.js';

import { evaluateGarrisonAndDetachments, evaluateReserve, evaluateHold } from './bot_brigade_eval_hold.js';
import { evaluateSectorMarch, evaluateReturnToCorps, evaluatePocketEvacuation, evaluateFrontCoverage } from './bot_brigade_eval_front.js';
import { evaluateHomeDefense, evaluateSupplyGate, evaluateSectorAttack, evaluateReorganize, evaluateDefensive, evaluateOffensive, evaluateUncontestedOccupation, UNCONTESTED_OCCUPATION_SCORE } from './bot_brigade_eval_attack.js';
import { evaluateInteriorMovement } from './bot_brigade_eval_movement.js';
import type { BrigadeEvaluationContext } from './bot_brigade_eval_types.js';

import type { OsidEthnicComposition } from './ethnic_defense.js';
import { COUNTER_ATTACK_RETREAT_WINDOW } from './bot_constants.js';

/**
 * ═══════════════════════════════════════════════════════════════
 * OWNERSHIP: Canonical
 * DOMAIN:    Bot brigade order generation — directive-based execution
 * ═══════════════════════════════════════════════════════════════
 *
 * DECIDES:   Which order (attack/hold/march/cover/reorg) each brigade executes this turn
 * WRITES:    brigade_movement_orders (merged from all bot evaluations)
 * READS:     T1 directive (sector_assignment, stance, offensive_targets), sector sub-segments
 * MUST NOT:  override T1 sector assignment or reassign a brigade to a different corps
 *
 * UPSTREAM:  commander_loop.ts directive → bot_corps_directives.ts
 * DOWNSTREAM: osid_column_movement.ts (column march), brigade_movement_orders.ts (single-hop)
 *
 * TRUTH INVARIANTS:
 * - Respects connected-component boundaries (no cross-component movement)
 * - Faction personality expressed through CorpsDirective, not hardcoded brigade logic
 * - Brigades NEVER attack independently; attack orders require valid CorpsOperation
 *
 * MOVEMENT TIER: T2 — Tactical Routing (Bot Brigade AI) (see MOVEMENT_AUTHORITY.md)
 * ═══════════════════════════════════════════════════════════════
 */

// ═══════════════════════════════════════════════════════════════════════════
// Submodule imports
// ═══════════════════════════════════════════════════════════════════════════

import {
    getFactionBrigades,
    findBrigadeSectorId,
    getAdjacentEnemyOsids,
    findNearestFriendlyOsidInSet,
    countCorpsBrigadesAtOsid,
    countFactionBrigadesAtOsid,
    isMovementDestinationRisky,
    MAX_CORPS_BRIGADES_PER_OSID,
} from './bot_brigade_context.js';

import {
    findAdjacentFrontGap,
    findNearestFrontOsid,
    findNearestOsidByPattern,
    computeHopsToFront,
    findFrontDestinationForColumnMarch,
    issueInteriorMovement,
    osidContains,
    osidMatchesAny,
    COLUMN_MARCH_MIN_HOPS,
} from './bot_brigade_movement_ai.js';

import {
    scoreTargetFromDirective,
    estimateConcentratedOutcome,
    isOutcomeSufficientForAttack,
    outcomeRank,
    outcomeFromRank,
    MAX_ATTACKERS_PER_TARGET,
    OUTCOME_RANK,
} from './bot_brigade_targeting.js';

import {
    computeOsidEthnicComposition,
    getBrigadeSupplyState,
    getAttackerSupplyPenalty,
    getCoEthnicScore,
    getRsVsHrhbPenalty,
    RS_VS_HRHB_ATTACK_ALLOWLIST,
} from './bot_brigade_supply_ethnic.js';
import type {
    OsidBotContext,
    SupplyConnectivityByFaction,
} from './bot_brigade_supply_ethnic.js';

// ═══════════════════════════════════════════════════════════════════════════
// Re-exports — all public symbols from submodules
// ═══════════════════════════════════════════════════════════════════════════

export {
    // context
    getFactionBrigades,
    findBrigadeSectorId,
    getAdjacentEnemyOsids,
    findNearestFriendlyOsidInSet,
    countCorpsBrigadesAtOsid,
    countFactionBrigadesAtOsid,
    isMovementDestinationRisky,
    MAX_CORPS_BRIGADES_PER_OSID,
    // movement
    findAdjacentFrontGap,
    findNearestFrontOsid,
    findNearestOsidByPattern,
    computeHopsToFront,
    findFrontDestinationForColumnMarch,
    issueInteriorMovement,
    osidContains,
    osidMatchesAny,
    COLUMN_MARCH_MIN_HOPS,
    // targeting
    scoreTargetFromDirective,
    estimateConcentratedOutcome,
    isOutcomeSufficientForAttack,
    outcomeRank,
    outcomeFromRank,
    MAX_ATTACKERS_PER_TARGET,
    OUTCOME_RANK,
    // supply/ethnic
    computeOsidEthnicComposition,
    getBrigadeSupplyState,
    getAttackerSupplyPenalty,
    getCoEthnicScore,
    getRsVsHrhbPenalty,
    RS_VS_HRHB_ATTACK_ALLOWLIST,
};
export type { OsidBotContext, SupplyConnectivityByFaction };
export type { OsidEthnicComposition } from './ethnic_defense.js';

// ═══════════════════════════════════════════════════════════════════════════
// Types (owned by orchestrator)
// ═══════════════════════════════════════════════════════════════════════════

export interface OsidBotOrdersResult {
    posture_orders: Array<{ brigade_id: FormationId; posture: BrigadePosture }>;
    attack_orders: Record<FormationId, Osid>;
    /** Score for each attack order — used by attack share cap to trim lowest-priority attacks first. */
    attack_scores: Record<FormationId, number>;
    movement_orders: Record<FormationId, Osid>;
    /** Column march orders: brigade → distant destination OSID (multi-turn transit). */
    column_march_orders: Record<FormationId, Osid>;
    /** Diagnostics: operation participants that could directly attack the current objective this turn. */
    eligible_attackers_by_corps: Record<FormationId, number>;
}

export interface BotOrderGenerationDiagnostics {
    eligible_attackers_by_corps: Record<FormationId, number>;
}

interface BrigadeContext {
    formation: FormationState;
    loc: Osid;
    osidAnalysis: import('./osid_graph_analysis.js').OsidAnalysis | null;
    corpsStance: CorpsStance | null;
    adjacentEnemyOsids: Osid[];
}

// ═══════════════════════════════════════════════════════════════════════════
// Operation helpers (private to orchestrator)
// ═══════════════════════════════════════════════════════════════════════════

/** Find the axis a brigade belongs to, or null if flat/not found. */
export function getBrigadeAxis(op: CorpsOperation, brigadeId: FormationId): OperationAxis | null {
    if (!isMultiAxis(op)) return null;
    return op.axes!.find(a => a.assigned_brigades.includes(brigadeId)) ?? null;
}

/** Check if a brigade participates in the operation (axis-aware). */
export function isOperationParticipant(op: CorpsOperation, brigadeId: FormationId): boolean {
    if (isMultiAxis(op)) {
        return op.axes!.some(a => a.assigned_brigades.includes(brigadeId));
    }
    return op.participating_brigades.includes(brigadeId);
}

function isPinnedActiveOperationAttacker(state: GameState, brigadeId: FormationId): boolean {
    const brigade = state.military.formations?.[brigadeId];
    const corpsId = brigade?.corps_id;
    if (!corpsId) return false;
    const cmd = state.military.corps_command?.[corpsId];
    if (!cmd) return false;
    const activeOp = findBrigadeOperation(cmd, brigadeId);
    if (!activeOp) return false;
    if (activeOp.phase !== 'execution') return false;
    if (activeOp.type !== 'sector_attack' && activeOp.type !== 'probe') return false;
    return isOperationParticipant(activeOp, brigadeId);
}

export function applySectorOffensiveDirectiveOverride(
    directive: import('../../state/game_state.js').CorpsDirective,
    activeOp: import('../../state/game_state.js').CorpsOperation,
    brigadeId?: FormationId,
): import('../../state/game_state.js').CorpsDirective {
    if (activeOp.phase !== 'execution') {
        return directive;
    }
    // Multi-axis: use the brigade's axis objectives
    const axis = brigadeId ? getBrigadeAxis(activeOp, brigadeId) : null;
    const objectives = axis ? axis.objectives : (activeOp.objectives ?? []);
    const currentIdx = axis ? axis.current_objective_index : (activeOp.current_objective_index ?? 0);
    const currentObjective = objectives[currentIdx];
    if (typeof currentObjective !== 'string' || currentObjective.length === 0) {
        return directive;
    }
    return {
        ...directive,
        offensive_targets: [currentObjective],
    };
}

export function getSectorOffensiveCurrentObjective(
    activeOp: import('../../state/game_state.js').CorpsOperation | null | undefined,
    brigadeId?: FormationId,
): Osid | null {
    if (!activeOp) return null;
    const axis = brigadeId ? getBrigadeAxis(activeOp, brigadeId) : null;
    const objectives = axis ? axis.objectives : (activeOp.objectives ?? []);
    const currentIdx = axis ? axis.current_objective_index : (activeOp.current_objective_index ?? 0);
    const currentObjective = objectives[currentIdx];
    return typeof currentObjective === 'string' && currentObjective.length > 0
        ? currentObjective as Osid
        : null;
}

export function getSectorOffensiveApproachOsids(
    state: GameState,
    activeOp: import('../../state/game_state.js').CorpsOperation,
    faction: FactionId,
    adjacency: Map<Osid, Osid[]>,
    reverseMap: OperationalToCanonicalReverseMap,
    brigadeId?: FormationId,
): Set<Osid> {
    const axis = brigadeId ? getBrigadeAxis(activeOp, brigadeId) : null;
    const objectives = axis ? axis.objectives : (activeOp.objectives ?? []);
    const currentIdx = axis ? axis.current_objective_index : (activeOp.current_objective_index ?? 0);
    const approachOsids = new Set<Osid>();
    for (const objective of objectives.slice(currentIdx)) {
        for (const neighbor of getTacticalAdjacentOsids(state, objective as Osid, adjacency)) {
            const neighborController = getPoliticalControllerOSID(state, neighbor, reverseMap);
            if (neighborController === faction || isFriendlyFaction(neighborController, faction, state)) {
                approachOsids.add(neighbor);
            }
        }
        if (approachOsids.size > 0) {
            break;
        }
    }
    return approachOsids;
}

export function getSectorOffensiveProbeThreshold(
    activeOp: import('../../state/game_state.js').CorpsOperation,
    brigadeId?: FormationId,
): PredictedOutcome {
    const axis = brigadeId ? getBrigadeAxis(activeOp, brigadeId) : null;
    const momentum = axis ? (axis.momentum ?? 0) : (activeOp.momentum ?? 0);
    // If the operation has an explicit min_attack_outcome, respect it.
    if (activeOp.min_attack_outcome) return activeOp.min_attack_outcome;
    // Default: costly_victory (ratio ≥ 1.0) — no bot should attack expecting to lose.
    // With momentum ≥ 2: stalemate (≥ 0.7) — pressing advantage, already proven you can win.
    return momentum >= 2 ? 'stalemate' : 'costly_victory';
}

function isPartOfNamedOperation(state: GameState, formation: FormationState): boolean {
    if (!formation.corps_id || !state.military.corps_command) return false;
    const cmd = state.military.corps_command[formation.corps_id];
    if (!cmd) return false;
    const op = findBrigadeOperation(cmd, formation.id);
    if (!op) return false;
    return op.phase === 'execution' && isOperationParticipant(op, formation.id);
}

// ═══════════════════════════════════════════════════════════════════════════
// Directive-based brigade execution (HoI-style: corps decides, brigade executes)
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Execute corps directive for all brigades of a faction.
 * Unified for all factions — faction personality comes from the directive.
 *
 * Brigade decision flow:
 * 1. Hold OSID → DEFEND (corps says hold this position)
 * 2. Offensive target adjacent → evaluate attack using combat predictor
 * 3. Front coverage: fill gaps, spread along assigned front
 * 4. Interior: column march toward front
 * 5. Reserve: defend posture, ready to redeploy
 *
 * Deterministic: sorted brigade iteration, sorted target evaluation.
 */
function executeFactionDirectives(
    state: GameState,
    faction: FactionId,
    brigades: FormationState[],
    adjacency: Map<Osid, Osid[]>,
    reverseMap: OperationalToCanonicalReverseMap,
    terrainCache: Record<string, number>,
    graphAnalysis: FactionGraphAnalysis,
    supplyStateByOsid?: SupplyStateByOsidReport | null,
    ethnicMap?: OsidEthnicComposition,
    osidPopulationMap?: OsidPopulationMap
): OsidBotOrdersResult {
    const result: OsidBotOrdersResult = {
        posture_orders: [],
        attack_orders: {},
        attack_scores: {},
        movement_orders: {},
        column_march_orders: {},
        eligible_attackers_by_corps: {}
    };
    const chosenTargets = new Map<Osid, number>();
    const columnAssignments = new Map<Osid, number>();

    const corpsReserve = new Map<string, { total: number; reserved: number }>();
    for (const b of brigades) {
        if (!b.corps_id) continue;
        const existing = corpsReserve.get(b.corps_id) ?? { total: 0, reserved: 0 };
        existing.total++;
        corpsReserve.set(b.corps_id, existing);
    }

    const isAlliedWithRBiH = areRbihHrhbAllied(state);

    // ── Build sector retreat map for broadened counter-attacks ───────────
    // Scan all brigades for recent retreats; group by sector ID.
    // Determinism: iterate sorted brigades, sort retreat entries by OSID.
    const currentTurn = state.meta?.turn ?? 0;
    const sectorRecentRetreats = new Map<string, Array<{ osid: string; turn: number }>>();
    for (const b of brigades) {
        const retreatInfo = (b as { last_retreat_from?: { osid: string; turn: number } }).last_retreat_from;
        if (!retreatInfo || retreatInfo.turn < currentTurn - COUNTER_ATTACK_RETREAT_WINDOW) continue;
        const sectorId = findBrigadeSectorId(state, b);
        if (!sectorId) continue;
        let arr = sectorRecentRetreats.get(sectorId);
        if (!arr) {
            arr = [];
            sectorRecentRetreats.set(sectorId, arr);
        }
        // Avoid duplicate OSIDs within the same sector
        if (!arr.some(e => e.osid === retreatInfo.osid && e.turn === retreatInfo.turn)) {
            arr.push({ osid: retreatInfo.osid, turn: retreatInfo.turn });
        }
    }
    // Sort each sector's retreat entries by OSID for determinism
    for (const [, arr] of sectorRecentRetreats) {
        arr.sort((a, b) => strictCompare(a.osid, b.osid));
    }
    const sectorCounterAttackCount = new Map<string, number>();

    const targetAdjacentCount = new Map<Osid, number>();
    for (const b of brigades) {
        if (!b.location_osid) continue;
        const adj = adjacency.get(b.location_osid) ?? [];
        for (const n of adj) {
            targetAdjacentCount.set(n, (targetAdjacentCount.get(n) ?? 0) + 1);
        }
    }

    for (const brigade of brigades) {
        const loc = brigade.location_osid!;
        // Loaned elites use their target corps for command lookups —
        // their corps_id is still the main staff (which has no operations).
        const loanedTo = brigade.elite_loan_state?.on_loan ? brigade.elite_loan_state.loaned_to_corps : null;
        const corpsId = loanedTo ?? brigade.corps_id;
        const cmd = corpsId ? state.military.corps_command?.[corpsId] : null;
        const activeOp = cmd ? findBrigadeOperation(cmd, brigade.id) : null;
        const isActiveSectorOperationParticipant =
            (activeOp?.type === 'sector_attack' || activeOp?.type === 'probe') &&
            isOperationParticipant(activeOp, brigade.id);
            
        const directive = cmd?.directive ?? null;
        const corpsStance = cmd?.stance ?? 'balanced';
        const adjEnemy = getAdjacentEnemyOsids(loc, faction, adjacency, state, reverseMap);

        const retreatInfo = (brigade as { last_retreat_from?: { osid: string; turn: number } }).last_retreat_from;
        const currentTurn = state.meta?.turn ?? 0;
        const counterAttackTarget: Osid | null = (retreatInfo && retreatInfo.turn === currentTurn - 1)
            ? retreatInfo.osid as Osid : null;

        const rawOsidSupplyState = getBrigadeSupplyState(brigade, supplyStateByOsid);
        const factionReserveLevel = state.meta?.supply_reserves_enabled
            ? ((state.military.general_supply_reserve as Record<string, number> | undefined)?.[brigade.faction] ?? 100)
            : 100;
        const brigadeSupplyState = state.meta?.supply_reserves_enabled
            ? getEffectiveSupplyState(rawOsidSupplyState, factionReserveLevel)
            : rawOsidSupplyState;

        const ctx: BrigadeEvaluationContext = {
            state,
            faction,
            brigade,
            loc,
            corpsId,
            cmd: cmd ?? null,
            directive,
            corpsStance,
            activeOp,
            isActiveSectorOperationParticipant,
            adjEnemy,
            isAlliedWithRBiH,
            targetAdjacentCount,
            corpsReserve,
            chosenTargets,
            columnAssignments,
            counterAttackTarget,
            brigadeSupplyState,
            isHoldBrigade: false,
            sectorRecentRetreats,
            sectorCounterAttackCount,
            adjacency,
            reverseMap,
            terrainCache,
            graphAnalysis,
            supplyStateByOsid,
            ethnicMap,
            osidPopulationMap,
            result
        };

        // Skip brigades already in column transit — re-issuing orders resets progress.
        const existingTransit = state.military.brigade_movement_state?.[brigade.id];
        if (existingTransit?.stance === 'column' && existingTransit?.status === 'in_transit') {
            result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
            continue;
        }
        if (evaluateGarrisonAndDetachments(ctx)) continue;
        if (evaluateSectorMarch(ctx)) continue;
        if (evaluateReturnToCorps(ctx)) continue; // Before hold/defense — orphans march home first
        if (evaluatePocketEvacuation(ctx)) continue; // Evacuate tiny non-enclave pockets
        if (evaluateHomeDefense(ctx)) continue;
        if (evaluateReserve(ctx)) continue;
        if (evaluateSupplyGate(ctx)) continue;
        if (evaluateSectorAttack(ctx)) continue;
        if (evaluateUncontestedOccupation(ctx)) continue;
        if (evaluateHold(ctx)) continue;
        if (evaluateReorganize(ctx)) continue;
        if (evaluateDefensive(ctx)) continue;
        if (evaluateOffensive(ctx)) continue;
        if (evaluateFrontCoverage(ctx)) continue;
        evaluateInteriorMovement(ctx);
    }

    return result;
}

// ═══════════════════════════════════════════════════════════════════════════
// Main entry point
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Generate bot brigade orders for all bot factions using directive-based execution.
 *
 * Brigades read their corps directive (generated by generate-bot-corps-orders)
 * and execute: attack directive targets, hold positions, cover front, move to front.
 *
 * Replaces the three faction-specific AIs (VRS/ARBiH/HVO) with one unified executor.
 * Faction personality is expressed through the CorpsDirective (what targets, what thresholds).
 *
 * Deterministic: faction processing in sorted order, brigades sorted by ID.
 */
export function generateAllBotOrdersOsid(
    state: GameState,
    botFactions: FactionId[],
    ctx: OsidBotContext
): BotOrderGenerationDiagnostics {
    const adjacency = (ctx.adjacency as Map<Osid, Osid[]>) ?? buildOsidAdjacency(ctx.edges);
    const terrainCache = buildTerrainCache(ctx.reverseMap);
    const sortedFactions = [...botFactions].sort(strictCompare);

    const allAttackOrders: Record<FormationId, Osid> = {};
    const allPostureOrders: Array<{ brigade_id: FormationId; posture: BrigadePosture }> = [];
    const allMovementOrders: Record<FormationId, Osid> = {};
    const allColumnMarchOrders: Record<FormationId, Osid> = {};
    const allEligibleAttackersByCorps: Record<FormationId, number> = {};

    for (const faction of sortedFactions) {
        const fmtsBrigades = state.military.formations ?? {};
        const brigades = Object.keys(fmtsBrigades).sort(strictCompare).map(k => fmtsBrigades[k]!)
            .filter((f): f is FormationState =>
                f != null &&
                f.faction === faction &&
                f.status === 'active' &&
                (f.kind === 'brigade' || f.kind === 'og' || f.kind === 'operational_group' || f.kind === 'militia' || f.kind === 'jna_phantom' || f.kind === 'hv_phantom') &&
                f.location_osid != null
            );

        if (brigades.length === 0) continue;

        const graphAnalysis = analyzeFactionGraph(state, faction, adjacency, ctx.reverseMap);

        const result = executeFactionDirectives(
            state, faction, brigades, adjacency, ctx.reverseMap,
            terrainCache, graphAnalysis,
            ctx.supplyStateByOsid, ctx.ethnicCompositionByOsid, ctx.osidPopulationMap
        );

        // Per-corps attack share cap: each corps gets attack slots proportional to its size.
        // This prevents large corps (1KK with 28 brigades) from monopolizing all attack slots
        // while small corps (Drina with 6 brigades) get zero.
        // Within each corps, trim lowest-scoring attacks first.
        // Winter: attack_share_mult reduces effective slots (near-total stasis Dec-Jan).
        const turn = state.meta?.turn ?? 0;
        const seasonal = getSeasonalModifiers(turn, state.meta?.scenario_start_date);
        const maxAttackShare = getEffectiveAttackShare(faction, turn, state.military.war_timeline) * seasonal.attack_share_mult;

        // Count brigades per corps
        const corpsSize = new Map<string, number>();
        for (const b of brigades) {
            const cid = b.corps_id ?? '__nocorps__';
            corpsSize.set(cid, (corpsSize.get(cid) ?? 0) + 1);
        }

        // Group attack entries by corps, with scores
        const attacksByCorps = new Map<string, Array<{ bid: FormationId; target: Osid; score: number }>>();
        for (const [bid, target] of Object.entries(result.attack_orders)) {
            if (target == null) continue;
            const brig = state.military.formations?.[bid as FormationId];
            const cid = brig?.corps_id ?? '__nocorps__';
            if (!attacksByCorps.has(cid)) attacksByCorps.set(cid, []);
            attacksByCorps.get(cid)!.push({
                bid: bid as FormationId,
                target: target as Osid,
                score: result.attack_scores[bid as FormationId] ?? 0
            });
        }

        // Per-corps trimming: each corps gets max(1, floor(size * attackShare)) slots
        for (const [cid, attacks] of [...attacksByCorps.entries()].sort((a, b) => strictCompare(a[0], b[0]))) {
            const size = corpsSize.get(cid) ?? 1;
            const maxCorpsAttacks = Math.max(1, Math.floor(size * maxAttackShare));
            if (attacks.length <= maxCorpsAttacks) continue;

            // Sort by score DESC, deterministic tiebreak
            attacks.sort((a, b) => {
                if (b.score !== a.score) return b.score - a.score;
                return strictCompare(a.bid, b.bid);
            });
            const pinned = attacks.filter((entry) => isPinnedActiveOperationAttacker(state, entry.bid));
            const trimmable = attacks.filter((entry) =>
                !isPinnedActiveOperationAttacker(state, entry.bid)
                && entry.score !== UNCONTESTED_OCCUPATION_SCORE
            );
            const keepTrimmable = Math.max(0, maxCorpsAttacks - pinned.length);
            const trimmed = trimmable.slice(keepTrimmable);
            for (const entry of trimmed) {
                delete result.attack_orders[entry.bid];
                delete result.attack_scores[entry.bid];
                result.posture_orders.push({ brigade_id: entry.bid, posture: 'hold' });
            }
        }

        // C.2: ARBiH warlord friction — before w78, one attacking brigade per corps
        // is forced to defend each turn (deterministic: turn % attackingBrigadeCount).
        // Simulates lack of unified command / warlord autonomy in early ARBiH.
        // D.4: Read warlord friction end week from war_timeline if available
        const warlordFrictionEndWeek = state.military.war_timeline?.officer_config?.RBiH?.warlord_friction_end_week ?? 78;
        if (faction === 'RBiH' && turn < warlordFrictionEndWeek) {
            for (const [cid, attacks] of [...attacksByCorps.entries()].sort((a, b) => strictCompare(a[0], b[0]))) {
                const trimmable = attacks.filter((entry) =>
                    !isPinnedActiveOperationAttacker(state, entry.bid)
                    && entry.score !== UNCONTESTED_OCCUPATION_SCORE
                );
                if (trimmable.length <= 1) continue; // Need at least 2 non-operation attackers for friction
                // Sort by bid for deterministic selection
                const sorted = [...trimmable].sort((a, b) => strictCompare(a.bid, b.bid));
                const frictionIndex = turn % sorted.length;
                const frictionTarget = sorted[frictionIndex]!;
                // Remove from attack orders, force hold (warlord friction: unit refuses orders)
                delete result.attack_orders[frictionTarget.bid];
                delete result.attack_scores[frictionTarget.bid];
                result.posture_orders.push({ brigade_id: frictionTarget.bid, posture: 'hold' });
            }
        }

        // Accumulate results
        const finalEligibleAttackersByCorps: Record<FormationId, number> = {};
        for (const bid of Object.keys(result.attack_orders).sort(strictCompare)) {
            const brig = state.military.formations?.[bid as FormationId];
            const corpsId = brig?.corps_id;
            if (!corpsId) continue;
            finalEligibleAttackersByCorps[corpsId] = (finalEligibleAttackersByCorps[corpsId] ?? 0) + 1;
        }
        allPostureOrders.push(...result.posture_orders);
        for (const [bid, target] of Object.entries(result.attack_orders)) {
            if (target != null) allAttackOrders[bid as FormationId] = target;
        }
        for (const [bid, dest] of Object.entries(result.movement_orders)) {
            if (dest != null) allMovementOrders[bid as FormationId] = dest;
        }
        for (const [bid, dest] of Object.entries(result.column_march_orders)) {
            if (dest != null) allColumnMarchOrders[bid as FormationId] = dest;
        }
        for (const corpsId of Object.keys(finalEligibleAttackersByCorps).sort(strictCompare)) {
            allEligibleAttackersByCorps[corpsId] =
                (allEligibleAttackersByCorps[corpsId] ?? 0) + finalEligibleAttackersByCorps[corpsId]!;
        }
    }

    // ── Graz Accords enforcement: remove RS↔HRHB attacks violating ceasefire ──
    // Exception: brigades in a corps with an active operation AND the east Herzegovina
    // pair truce hasn't activated yet (Op Jackal still running) are exempt.
    if (isGrazAccordsActive(state)) {
        const pc = state.political.political_controllers ?? {};
        const formations = state.military.formations ?? {};
        const corpsCmd = state.military.corps_command ?? {};
        for (const bid of Object.keys(allAttackOrders)) {
            const target = allAttackOrders[bid as FormationId];
            if (!target) continue;
            const f = formations[bid];
            if (!f) continue;
            const corpsId = f.corps_id ?? '';
            const faction = f.faction as FactionId;
            const targetController = pc[target] ?? '';
            // Skip Graz block for brigades attacking Op Jackal objectives only
            const grazCmd = corpsCmd[corpsId];
            if (grazCmd && grazCmd.active_operations.length > 0
                && isEastHerzegovinaPair(corpsId)
                && state.political.graz_east_herzegovina_active_turn == null) {
                // Check if target is an objective of any active operation
                let isOpObjective = false;
                for (const op of grazCmd.active_operations) {
                    const opObjectives = new Set(
                        op.axes?.flatMap(a => a.objectives ?? []) ?? op.objectives ?? []
                    );
                    if (opObjectives.has(target)) { isOpObjective = true; break; }
                }
                if (isOpObjective) continue; // Target is an op objective — allow
                // Non-objective RS targets still blocked by Graz
            }
            if (shouldGrazBlockAttack(state, corpsId, faction, target, targetController)) {
                delete allAttackOrders[bid as FormationId];
            }
        }
    }

    // Write to state
    if (!state.military.brigade_posture_orders) state.military.brigade_posture_orders = [];
    state.military.brigade_posture_orders.push(...allPostureOrders);

    if (Object.keys(allAttackOrders).length > 0) {
        state.military.brigade_attack_orders = allAttackOrders;
    }

    // Movement orders: merge regular moves + column march destinations
    const mergedMovement: Record<string, { destination_sids: string[]; stance?: string }> = {};
    for (const [bid, dest] of Object.entries(allMovementOrders)) {
        mergedMovement[bid] = { destination_sids: [dest] };
    }
    for (const [bid, dest] of Object.entries(allColumnMarchOrders)) {
        // Column march: write to movement orders with stance:'column' so the
        // column movement processor (processOsidColumnMovement) picks them up.
        mergedMovement[bid] = { destination_sids: [dest], stance: 'column' };
    }
    if (Object.keys(mergedMovement).length > 0) {
        state.military.brigade_movement_orders = mergedMovement as Record<FormationId, { destination_sids: string[]; stance?: string }>;
    }

    return {
        eligible_attackers_by_corps: allEligibleAttackersByCorps
    };
}
