/**
 * release_notes_generator.test.ts
 *
 * Validates tools/release/generate_release_notes.cjs:
 *   T1: extraction since tag — output is a string with expected section headers.
 *       When commits in the window include conventional types, those sections
 *       contain at least one entry; the boilerplate header is always present.
 *   T2: idempotent / deterministic — two consecutive runs against the same
 *       range produce byte-identical output.
 *   T3: no Math.random / Date.now / new Date / performance.now / process.hrtime
 *       in the generator source (static-grep guard).
 *   T4: byte-compare sort is used for tied subjects (no localeCompare anywhere
 *       in the generator source).
 *
 * Part of LANE-V095-RELEASE-NOTES-GENERATOR (closes audit P2-G3).
 */
import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

const TOOL_PATH = path.resolve(
    __dirname,
    '..',
    'tools',
    'release',
    'generate_release_notes.cjs',
);

function runGenerator(args: string[]): string {
    return execFileSync(process.execPath, [TOOL_PATH, ...args], {
        encoding: 'utf8',
        // generator writes to stdout; bound a generous buffer for repos with
        // many commits in the window.
        maxBuffer: 16 * 1024 * 1024,
    });
}

describe('tools/release/generate_release_notes.cjs', () => {
    it('T1: extracts commits since a stable window and emits expected section headers', () => {
        // HEAD~5 is a stable window — 5 commits behind whatever HEAD is when the
        // test runs. Determinism comes from "same repo state -> same output",
        // not from "specific commit set".
        const out = runGenerator(['--from-tag', 'HEAD~5']);
        expect(typeof out).toBe('string');
        expect(out.length).toBeGreaterThan(0);

        // Always-present scaffold:
        expect(out).toContain('# AWWV HEAD');
        expect(out).toContain('Built from HEAD~5..HEAD.');
        expect(out).toContain('## Highlights');
        expect(out).toContain('## Features');
        expect(out).toContain('## Fixes');
        expect(out).toContain('## Performance');
        expect(out).toContain('## Other');
        expect(out).toContain(
            'Auto-generated by tools/release/generate_release_notes.cjs.',
        );
    });

    it('T2: idempotent — two runs against the same range produce byte-identical output', () => {
        const a = runGenerator(['--from-tag', 'HEAD~5']);
        const b = runGenerator(['--from-tag', 'HEAD~5']);
        expect(a).toBe(b);
        // Reinforce byte-equality via length too (cheap secondary check).
        expect(a.length).toBe(b.length);
    });

    it('T3: generator source has no Math.random / Date / performance.now / process.hrtime', () => {
        const src = fs.readFileSync(TOOL_PATH, 'utf8');
        // Strip block + line comments so banned tokens in the determinism-contract
        // doc-comment do not falsely trigger.
        const stripped = src
            .replace(/\/\*[\s\S]*?\*\//g, '')
            .split('\n')
            .map((line) => {
                const idx = line.indexOf('//');
                return idx >= 0 ? line.slice(0, idx) : line;
            })
            .join('\n');

        expect(stripped).not.toMatch(/Math\.random/);
        expect(stripped).not.toMatch(/Date\.now/);
        expect(stripped).not.toMatch(/new Date\b/);
        expect(stripped).not.toMatch(/performance\.now/);
        expect(stripped).not.toMatch(/process\.hrtime/);
    });

    it('T4: generator uses byte-compare (not localeCompare) for tie-breaks', () => {
        const src = fs.readFileSync(TOOL_PATH, 'utf8');
        const stripped = src
            .replace(/\/\*[\s\S]*?\*\//g, '')
            .split('\n')
            .map((line) => {
                const idx = line.indexOf('//');
                return idx >= 0 ? line.slice(0, idx) : line;
            })
            .join('\n');

        // Forbidden:
        expect(stripped).not.toMatch(/localeCompare/);

        // Required: explicit byteCompare implementation (lhs<rhs branches).
        expect(src).toContain('function byteCompare');
        expect(src).toMatch(/a < b \? -1 : a > b \? 1 : 0|if \(a < b\) return -1/);
    });
});
