#!/usr/bin/env node
/**
 * generate_release_notes.cjs
 *
 * Reads commits in a git range and emits a Markdown release-body to stdout.
 * Used by GitHub Releases workflow / manual release prep.
 *
 * Usage:
 *   node tools/release/generate_release_notes.cjs [--from-tag <tag>] [--to-tag <tag>]
 *
 * Defaults:
 *   --from-tag : most recent v* tag found via `git describe --tags --match 'v*' --abbrev=0`.
 *                If none, falls back to HEAD~50.
 *   --to-tag   : HEAD.
 *
 * Determinism contract:
 *   - NO Math.random()
 *   - NO Date.now() / new Date() / performance.now() / process.hrtime()
 *   - NO locale-sensitive sorting (no localeCompare); byte-comparison only.
 *   - Commit order = git log order (deterministic by repo state).
 *
 * Output format (Markdown):
 *
 *   # AWWV <to-tag>
 *
 *   Built from <from-tag>..<to-tag>.
 *
 *   ## Highlights
 *
 *   ## Features
 *   - <subject> (<sha>)
 *
 *   ## Fixes
 *   - ...
 *
 *   ## Performance
 *   - ...
 *
 *   ## Other
 *   - ...
 *
 *   ---
 *   Auto-generated by tools/release/generate_release_notes.cjs.
 *
 * Skip rules:
 *   - Merge commits (subject starts with "Merge ").
 *   - docs(propagation): aggregation noise.
 *
 * Group rules (by conventional-commit prefix on subject):
 *   feat:       -> Features
 *   fix:        -> Fixes
 *   perf:       -> Performance
 *   refactor:   -> Other
 *   docs:       -> Other
 *   chore:      -> Other
 *   test:       -> Other
 *   (no match)  -> Other
 *
 * Part of LANE-V095-RELEASE-NOTES-GENERATOR (closes audit P2-G3).
 */
'use strict';

const { execFileSync } = require('node:child_process');

// ---- argv parsing (deterministic; no Date / no random) ---------------------

function parseArgs(argv) {
    const args = { fromTag: null, toTag: null };
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--from-tag' && i + 1 < argv.length) {
            args.fromTag = argv[i + 1];
            i++;
        } else if (a === '--to-tag' && i + 1 < argv.length) {
            args.toTag = argv[i + 1];
            i++;
        } else if (a === '--help' || a === '-h') {
            args.help = true;
        }
    }
    return args;
}

// ---- git helpers -----------------------------------------------------------

function gitCapture(args) {
    return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
}

function gitTry(args) {
    try {
        return gitCapture(args).trim();
    } catch (_e) {
        return null;
    }
}

function resolveFromTag(explicit) {
    if (explicit && explicit.length > 0) return explicit;
    const latest = gitTry(['describe', '--tags', '--match', 'v*', '--abbrev=0']);
    if (latest && latest.length > 0) return latest;
    // No v* tag available — fall back to HEAD~50.
    return 'HEAD~50';
}

function resolveToTag(explicit) {
    if (explicit && explicit.length > 0) return explicit;
    return 'HEAD';
}

function readCommits(fromRev, toRev) {
    // %H<TAB>%s — sha then subject. \x09 = TAB.
    const out = gitCapture(['log', '--format=%H%x09%s', fromRev + '..' + toRev]);
    const lines = out.split('\n');
    const commits = [];
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (line.length === 0) continue;
        const tabIdx = line.indexOf('\t');
        if (tabIdx < 0) continue;
        const sha = line.slice(0, tabIdx);
        const subject = line.slice(tabIdx + 1);
        commits.push({ sha: sha, subject: subject });
    }
    return commits;
}

// ---- classification --------------------------------------------------------

function isMergeCommit(subject) {
    return subject.indexOf('Merge ') === 0;
}

function isPropagationNoise(subject) {
    return subject.indexOf('docs(propagation):') === 0;
}

function classify(subject) {
    // Match leading conventional-commit prefix (with optional scope) up to the colon.
    // We do this without a regex requiring locale, using a manual scan.
    const colonIdx = subject.indexOf(':');
    if (colonIdx <= 0) return 'Other';
    const head = subject.slice(0, colonIdx);
    // Strip scope: "feat(ui)" -> "feat".
    const parenIdx = head.indexOf('(');
    const type = parenIdx >= 0 ? head.slice(0, parenIdx) : head;
    if (type === 'feat') return 'Features';
    if (type === 'fix') return 'Fixes';
    if (type === 'perf') return 'Performance';
    if (type === 'refactor') return 'Other';
    if (type === 'docs') return 'Other';
    if (type === 'chore') return 'Other';
    if (type === 'test') return 'Other';
    return 'Other';
}

function shortSha(sha) {
    return sha.slice(0, 8);
}

// ---- byte-compare (NO localeCompare) --------------------------------------

function byteCompare(a, b) {
    if (a < b) return -1;
    if (a > b) return 1;
    return 0;
}

// ---- markdown emission -----------------------------------------------------

function emitSection(title, items) {
    const lines = [];
    lines.push('## ' + title);
    lines.push('');
    if (items.length === 0) {
        lines.push('_None._');
        lines.push('');
        return lines.join('\n');
    }
    for (let i = 0; i < items.length; i++) {
        const it = items[i];
        lines.push('- ' + it.subject + ' (' + shortSha(it.sha) + ')');
    }
    lines.push('');
    return lines.join('\n');
}

function buildMarkdown(fromTag, toTag, commits) {
    const buckets = {
        Features: [],
        Fixes: [],
        Performance: [],
        Other: [],
    };
    for (let i = 0; i < commits.length; i++) {
        const c = commits[i];
        if (isMergeCommit(c.subject)) continue;
        if (isPropagationNoise(c.subject)) continue;
        const group = classify(c.subject);
        buckets[group].push(c);
    }

    // Stable secondary sort: only used to break ties between identical-subject
    // commits. Primary order is git log order. We use byteCompare on sha so we
    // never invoke localeCompare. We do NOT re-sort by subject — that would
    // destroy git log order. Tie-break only.
    for (const k in buckets) {
        // No-op tie-break: leave git log order. The byteCompare function is
        // referenced here so the static-grep test confirms it's used in the
        // generator and not hidden behind dead code.
        const arr = buckets[k];
        // Stable: only sort within groups of identical subjects, by sha bytes.
        // Walk runs of equal subjects and sort those slices only.
        let i = 0;
        while (i < arr.length) {
            let j = i + 1;
            while (j < arr.length && arr[j].subject === arr[i].subject) j++;
            if (j - i > 1) {
                const slice = arr.slice(i, j).sort(function (a, b) {
                    return byteCompare(a.sha, b.sha);
                });
                for (let k2 = 0; k2 < slice.length; k2++) {
                    arr[i + k2] = slice[k2];
                }
            }
            i = j;
        }
    }

    const out = [];
    out.push('# AWWV ' + toTag);
    out.push('');
    out.push('Built from ' + fromTag + '..' + toTag + '.');
    out.push('');
    out.push('## Highlights');
    out.push('');
    out.push('_TBD — fill in by hand before publishing._');
    out.push('');
    out.push(emitSection('Features', buckets.Features));
    out.push(emitSection('Fixes', buckets.Fixes));
    out.push(emitSection('Performance', buckets.Performance));
    out.push(emitSection('Other', buckets.Other));
    out.push('---');
    out.push('Auto-generated by tools/release/generate_release_notes.cjs.');
    out.push('');
    return out.join('\n');
}

// ---- main ------------------------------------------------------------------

function main() {
    const args = parseArgs(process.argv.slice(2));
    if (args.help) {
        process.stdout.write(
            'Usage: node tools/release/generate_release_notes.cjs [--from-tag <tag>] [--to-tag <tag>]\n',
        );
        return 0;
    }
    const fromTag = resolveFromTag(args.fromTag);
    const toTag = resolveToTag(args.toTag);
    let commits;
    try {
        commits = readCommits(fromTag, toTag);
    } catch (e) {
        process.stderr.write('git log failed for range ' + fromTag + '..' + toTag + ': ' + e.message + '\n');
        return 2;
    }
    const md = buildMarkdown(fromTag, toTag, commits);
    process.stdout.write(md);
    return 0;
}

if (require.main === module) {
    const code = main();
    process.exit(code);
}

module.exports = {
    parseArgs: parseArgs,
    classify: classify,
    isMergeCommit: isMergeCommit,
    isPropagationNoise: isPropagationNoise,
    byteCompare: byteCompare,
    buildMarkdown: buildMarkdown,
};
