import type { GameState } from '../../../state/game_state.js';
import { extractWarData } from '../data/war_data_extractor.js';
import { getPlayerFaction, turnToDateString } from './warroom_utils.js';
import { getWarroomFactionIdentity } from './warroom_identity.js';

export class CommandBriefingModal {
    private gameState: GameState;

    constructor(gameState: GameState) {
        this.gameState = gameState;
    }

    render(): HTMLElement {
        const factionId = getPlayerFaction(this.gameState) || 'RBiH';
        const isWar = this.gameState.meta.phase === 'war';
        const identity = getWarroomFactionIdentity(factionId);
        
        const container = document.createElement('div');
        container.className = 'wr-modal-newspaper wr-paper-texture';
        container.style.maxWidth = '800px';

        let content = '';

        if (!isWar) {
            content = `
                <div style="font-family: 'Courier New', Courier, monospace; color: #111;">
                    <h2 style="border-bottom: 2px solid #111; padding-bottom: 10px;">COMMAND BRIEFING: PRE-WAR SITUATION</h2>
                    <p style="font-weight: bold; margin-bottom: 20px;">CLASSIFICATION: SECRET</p>
                    
                    <div style="margin-bottom: 20px;">
                        <h3 style="background: #333; color: #fff; padding: 5px;">> URGENT MATTERS</h3>
                        <ul>
                            <li>Political tensions are rising. Maintain organizational penetration.</li>
                            <li>Ensure key municipalities are secured before hostilities erupt.</li>
                            <li>Monitor opponent paramilitaries assembling near the borders.</li>
                        </ul>
                    </div>

                    <div style="margin-bottom: 20px;">
                        <h3 style="background: #333; color: #fff; padding: 5px;">> LOGISTICS & SUPPLY</h3>
                        <p>Awaiting authorization for widespread mobilization. Supply caches remain sealed.</p>
                    </div>
                </div>
            `;
        } else {
            const warData = extractWarData(this.gameState, factionId);
            const currentDate = turnToDateString(this.gameState.meta.turn);
            
            const routedBrigades = warData.ownForces.formationDetails.filter(f => f.posture === 'routed').length;
            const cutOffBrigades = warData.brigadeMovement.encircled.length;
            const starvingBrigades = warData.ownSupply.criticalCount;
            
            content = `
                <div style="font-family: 'Courier New', Courier, monospace; color: #111;">
                    <h2 style="border-bottom: 2px solid #111; padding-bottom: 10px;">COMMAND BRIEFING: ${currentDate}</h2>
                    <p style="font-weight: bold; margin-bottom: 20px;">CLASSIFICATION: TOP SECRET / EYES ONLY</p>
                    
                    <div style="margin-bottom: 20px;">
                        <h3 style="background: #333; color: #fff; padding: 5px;">> WHAT MATTERS NOW</h3>
                        <ul style="line-height: 1.6;">
                            ${routedBrigades > 0 ? `<li style="color: darkred; font-weight: bold;">CRITICAL: ${routedBrigades} Brigades routed in recent engagements.</li>` : ''}
                            <li>${starvingBrigades > 0 ? `${starvingBrigades} brigades report critical supply shortages (STARVING).` : 'Supply lines currently stable. No brigades starving.'}</li>
                            <li>${cutOffBrigades > 0 ? `${cutOffBrigades} brigades are CUT OFF from main HQ.` : 'All units maintain contact with HQs.'}</li>
                            <li>Current Force: ${warData.ownForces.totalPersonnel.toLocaleString()} personnel active.</li>
                        </ul>
                    </div>

                    <div style="margin-bottom: 20px;">
                        <h3 style="background: #333; color: #fff; padding: 5px;">> ENCLAVE WARNINGS</h3>
                        <p>No critical enclaves nearing collapse this week. Continue monitoring isolated pockets.</p>
                    </div>

                    <div style="margin-bottom: 20px;">
                        <h3 style="background: #333; color: #fff; padding: 5px;">> CONVOY STATUS</h3>
                        <p>UNHCR humanitarian convoys are moving with minimal disruption. Military logistics corridors to primary fronts remain open.</p>
                    </div>

                    <div style="margin-top: 40px; border-top: 1px dashed #666; padding-top: 10px; font-size: 12px; text-align: right;">
                        Generated by ${identity.commandBriefLabel}
                    </div>
                </div>
            `;
        }

        container.innerHTML = content;
        return container;
    }
}
