import type { GameState } from '../../../state/game_state.js';
import { toCommandBriefingView } from '../../shared/command_briefing_views.js';
import { getPlayerFaction, turnToDateString } from './warroom_utils.js';
import { getWarroomFactionIdentity } from './warroom_identity.js';

function escapeHtml(value: string): string {
    return value
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;');
}

/**
 * CommandBriefingModal — Warroom command briefing surface.
 *
 * DATA BOUNDARY: the only permitted direct gameState read beyond meta.* fields is
 * military.last_briefing (line ~55). This is acceptable: last_briefing is a pre-computed
 * engine message packet, not raw operational data. Do not add further military.* or
 * political.* reads.
 */
export class CommandBriefingModal {
    private gameState: GameState;

    constructor(gameState: GameState) {
        this.gameState = gameState;
    }

    render(): HTMLElement {
        const factionId = getPlayerFaction(this.gameState) || 'RBiH';
        const isWar = this.gameState.meta.phase === 'war';
        const identity = getWarroomFactionIdentity(factionId);

        const container = document.createElement('div');
        container.className = 'wr-modal-newspaper wr-paper-texture';
        container.style.maxWidth = '800px';

        if (!isWar) {
            container.innerHTML = `
                <div style="font-family: 'Courier New', Courier, monospace; color: #111;">
                    <h2 style="border-bottom: 2px solid #111; padding-bottom: 10px;">COMMAND BRIEFING: PRE-WAR SITUATION</h2>
                    <p style="font-weight: bold; margin-bottom: 20px;">CLASSIFICATION: SECRET</p>

                    <div style="margin-bottom: 20px;">
                        <h3 style="background: #333; color: #fff; padding: 5px;">> URGENT MATTERS</h3>
                        <ul>
                            <li>Political tensions are rising. Maintain organizational penetration.</li>
                            <li>Ensure key municipalities are secured before hostilities erupt.</li>
                            <li>Monitor opponent paramilitaries assembling near the borders.</li>
                        </ul>
                    </div>

                    <div style="margin-bottom: 20px;">
                        <h3 style="background: #333; color: #fff; padding: 5px;">> LOGISTICS & SUPPLY</h3>
                        <p>Awaiting authorization for widespread mobilization. Supply caches remain sealed.</p>
                    </div>
                </div>
            `;
            return container;
        }

        const rawBriefing = this.gameState.military?.last_briefing;
        const briefing = rawBriefing && rawBriefing.faction === factionId
            ? toCommandBriefingView(rawBriefing)
            : undefined;
        const currentDate = turnToDateString(this.gameState.meta.turn);
        const items = briefing?.items ?? [];
        const itemsHtml = items.length > 0
            ? items.map((item) => {
                const tone = item.severity === 'critical'
                    ? 'font-weight: bold;'
                    : item.severity === 'warning'
                        ? 'font-style: italic;'
                        : '';
                const detail = item.detail ? ` <span>${escapeHtml(item.detail)}</span>` : '';
                return `<li style="${tone}">${escapeHtml(item.title)}.${detail}</li>`;
            }).join('')
            : '<li>No command briefing packet is available yet. Advance the turn to generate the first staff summary.</li>';

        container.innerHTML = `
            <div style="font-family: 'Courier New', Courier, monospace; color: #111;">
                <h2 style="border-bottom: 2px solid #111; padding-bottom: 10px;">COMMAND BRIEFING: ${escapeHtml(currentDate)}</h2>
                <p style="font-weight: bold; margin-bottom: 20px;">CLASSIFICATION: TOP SECRET / EYES ONLY</p>

                <div style="margin-bottom: 20px;">
                    <h3 style="background: #333; color: #fff; padding: 5px;">> COMMAND SUMMARY</h3>
                    <p>${escapeHtml(briefing?.headline ?? 'No current command briefing is available.')}</p>
                </div>

                <div style="margin-bottom: 20px;">
                    <h3 style="background: #333; color: #fff; padding: 5px;">> WHAT MATTERS NOW</h3>
                    <ul style="line-height: 1.55; margin: 0; padding-left: 18px;">
                        ${itemsHtml}
                    </ul>
                </div>

                <div style="margin-top: 40px; border-top: 1px dashed #666; padding-top: 10px; font-size: 12px; text-align: right;">
                    Generated by ${escapeHtml(identity.commandBriefLabel)}
                </div>
            </div>
        `;

        return container;
    }
}
