/**
 * OSID-native bot brigade AI — directive-based execution (HoI-style).
 *
 * Brigades read their corps directive (generated by bot_corps_ai.ts) and execute:
 *   - Attack directive targets using combat predictor
 *   - Hold specified positions (chokepoints, enclaves)
 *   - Cover assigned front segments (fill gaps, spread along front)
 *   - Move from interior toward front
 *
 * Faction personality is expressed through CorpsDirective (what targets,
 * what thresholds, what reserve fraction) — brigade execution is faction-agnostic.
 *
 * All decisions operate in OSID space — no dependency on brigade_aor or
 * canonical settlement graphs.
 *
 * Deterministic: sorted iteration, no randomness, no timestamps.
 */

import type { EdgeRecord } from '../../map/settlements.js';
import type {
    BrigadePosture,
    CorpsStance,
    FactionId,
    FormationId,
    FormationState,
    GameState
} from '../../state/game_state.js';
import { getPoliticalControllerOSID } from '../../state/settlement_control.js';
import { strictCompare } from '../../state/validateGameState.js';
import type { OperationalToCanonicalReverseMap } from '../../data/operational_data.js';
import {
    predictAllAdjacentTargets,
    buildTerrainCache,
    OUTCOME_SCORE,
    type CombatPrediction,
    type PredictedOutcome
} from './combat_predictor.js';
import {
    analyzeFactionGraph,
    type FactionGraphAnalysis,
    type OsidAnalysis
} from './osid_graph_analysis.js';
import {
    buildOsidAdjacency,
    isBrigadeDeployed,
    isBrigadeInEnemyZoc,
    getValidRetreatDestinations,
    type Osid
} from './zoc.js';
import { areRbihHrhbAllied } from '../phase_i/alliance_update.js';
import type { SupplyStateByOsidReport } from '../../state/supply_state_derivation.js';
import type { SettlementEthnicityData } from '../../data/settlement_ethnicity.js';

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export interface OsidBotOrdersResult {
    posture_orders: Array<{ brigade_id: FormationId; posture: BrigadePosture }>;
    attack_orders: Record<FormationId, Osid>;
    movement_orders: Record<FormationId, Osid>;
    /** Column march orders: brigade → distant destination OSID (multi-turn transit). */
    column_march_orders: Record<FormationId, Osid>;
}

interface BrigadeContext {
    formation: FormationState;
    loc: Osid;
    osidAnalysis: OsidAnalysis | null;
    corpsStance: CorpsStance | null;
    isZocLocked: boolean;
    adjacentEnemyOsids: Osid[];
}

// ═══════════════════════════════════════════════════════════════════════════
// Shared helpers
// ═══════════════════════════════════════════════════════════════════════════

function getCorpsStance(state: GameState, formation: FormationState): CorpsStance | null {
    if (!formation.corps_id || !state.corps_command) return null;
    const corps = state.corps_command[formation.corps_id];
    return corps?.stance ?? null;
}

function getFactionBrigades(state: GameState, faction: FactionId): FormationState[] {
    const formations = state.formations ?? {};
    const result: FormationState[] = [];
    for (const [, f] of Object.entries(formations)) {
        if (f.faction !== faction) continue;
        if (f.status !== 'active') continue;
        if (f.kind !== 'brigade' && f.kind !== 'og' && f.kind !== 'operational_group') continue;
        if (!f.location_osid) continue;
        // Skip brigades in column transit (they're redeploying; no new orders)
        if (!isBrigadeDeployed(state, f.id)) continue;
        result.push(f);
    }
    result.sort((a, b) => strictCompare(a.id, b.id));
    return result;
}

/** Return adjacent enemy-controlled OSIDs for a brigade location. */
function getAdjacentEnemyOsids(
    loc: Osid,
    faction: FactionId,
    adjacency: Map<Osid, Osid[]>,
    state: GameState,
    reverseMap: OperationalToCanonicalReverseMap
): Osid[] {
    const neighbors = adjacency.get(loc) ?? [];
    const result: Osid[] = [];
    for (const n of neighbors) {
        const c = getPoliticalControllerOSID(state, n, reverseMap);
        if (c !== null && c !== faction) result.push(n);
    }
    return result.sort(strictCompare);
}

/** Count how many active brigades from the same corps are at a given OSID.
 * Corps-level rebalancing: a corps commander manages their own zone.
 * If corpsId is null/undefined, falls back to counting all faction brigades. */
function countCorpsBrigadesAtOsid(state: GameState, faction: FactionId, corpsId: FormationId | null | undefined, osid: Osid): number {
    const formations = state.formations ?? {};
    let count = 0;
    for (const f of Object.values(formations)) {
        if (f.faction !== faction) continue;
        if (f.status !== 'active') continue;
        if (f.kind !== 'brigade' && f.kind !== 'og' && f.kind !== 'operational_group') continue;
        if (f.location_osid !== osid) continue;
        if (corpsId) {
            // Corps-level: only count brigades from the same corps
            if (f.corps_id === corpsId) count++;
        } else {
            // No corps info: count all faction brigades
            count++;
        }
    }
    return count;
}

/** Maximum brigades per corps that should stay at one OSID before rebalancing.
 * Per-corps threshold: each corps should have at most 2 at one position
 * (1 attacking + 1 in reserve). More means the corps has excess to redeploy
 * within its zone. At corps boundary junctions, 2+2=4 total is acceptable
 * since those are natural concentration points. */
const MAX_CORPS_BRIGADES_PER_OSID = 2;

/** Count ALL faction brigades at an OSID (regardless of corps). Used for
 * front-line gap-fill: a brigade should move to cover an undefended neighbor
 * only if at least 1 other faction brigade remains behind. */
function countFactionBrigadesAtOsid(state: GameState, faction: FactionId, osid: Osid): number {
    const formations = state.formations ?? {};
    let count = 0;
    for (const f of Object.values(formations)) {
        if (f.faction !== faction) continue;
        if (f.status !== 'active') continue;
        if (f.kind !== 'brigade' && f.kind !== 'og' && f.kind !== 'operational_group') continue;
        if (f.location_osid !== osid) continue;
        count++;
    }
    return count;
}

/**
 * Front-line gap filling: find an adjacent friendly OSID that is on the front
 * (has enemy neighbors) but has NO friendly brigade ("undefended" or "critical").
 * Returns the gap OSID to move to, or null.
 *
 * Historical: all factions prioritized covering their line. Even VRS, with
 * smaller manpower, spread brigades thinly to maintain a continuous front.
 * Gaps invited enemy penetration and encirclement. ZoC linking provides some
 * coverage, but having a physical brigade is far better for defense.
 *
 * Deterministic: sorted neighbor iteration, returns first qualifying gap.
 */
function findAdjacentFrontGap(
    state: GameState,
    loc: Osid,
    faction: FactionId,
    adjacency: Map<Osid, Osid[]>,
    reverseMap: OperationalToCanonicalReverseMap,
    graphAnalysis: FactionGraphAnalysis
): Osid | null {
    const neighbors = (adjacency.get(loc) ?? []).slice().sort(strictCompare);
    for (const n of neighbors) {
        const ctrl = getPoliticalControllerOSID(state, n, reverseMap);
        if (ctrl !== faction) continue;
        const analysis = graphAnalysis.osid_analysis.get(n);
        if (!analysis) continue;
        // Must be a front OSID (has enemy neighbors) AND undefended/critical (no or few defenders)
        if (analysis.enemy_neighbors.length > 0 &&
            (analysis.classification === 'undefended' || analysis.classification === 'critical')) {
            // Don't move to a gap if it already has a faction brigade heading there
            const factionHere = countFactionBrigadesAtOsid(state, faction, n);
            if (factionHere === 0) return n;
        }
    }
    return null;
}

/** Maximum brigades that can attack the same target OSID.
 * Increased from 2→3 to allow corps-level concentration of force.
 * Historical: VRS regularly massed 3+ brigades for key operations
 * (Corridor 92, Gorazde, Bihac). The attack resolution system applies
 * coordination penalty (0.8× for 3+) to the summed power. */
const MAX_ATTACKERS_PER_TARGET = 3;

/**
 * Estimate whether a coordinated attack (with already-assigned co-attackers)
 * would achieve a better outcome than the individual prediction.
 *
 * When evaluating a target that already has 1+ brigade assigned to attack it,
 * estimate the combined power ratio. Each additional attacker contributes
 * roughly 65% of one attacker's power (after coordination penalty).
 *
 * Returns the estimated combined outcome, or null if no improvement.
 */
function estimateConcentratedOutcome(
    individualRatio: number,
    existingAttackers: number
): PredictedOutcome | null {
    if (existingAttackers <= 0) return null;
    // Each additional attacker adds ~65% of one brigade's power (coord penalty 0.8-0.9)
    // For attacker N+1 joining N existing: combined ratio ≈ individual × (1 + N × 0.65)
    // N=1: ×1.65 (2 brigades, coord penalty makes combined ~1.8/1.1 per individual)
    // N=2: ×2.30 (3 brigades, coord penalty makes combined ~2.4/1.04 per individual)
    const combinedRatioMult = 1 + existingAttackers * 0.65;
    const estimatedRatio = individualRatio * combinedRatioMult;
    // Classify using same thresholds as combat predictor
    if (estimatedRatio >= 2.0) return 'decisive_victory';
    if (estimatedRatio >= 1.5) return 'victory';
    if (estimatedRatio >= 1.0) return 'costly_victory';
    if (estimatedRatio >= 0.7) return 'stalemate';
    if (estimatedRatio >= 0.5) return 'repulsed';
    return 'catastrophic';
}

/** Check if OSID contains a string pattern (case-insensitive). */
function osidContains(osid: Osid, pattern: string): boolean {
    return osid.toLowerCase().includes(pattern.toLowerCase());
}

/** Check if any array of patterns match the OSID. */
function osidMatchesAny(osid: Osid, patterns: string[]): boolean {
    const lower = osid.toLowerCase();
    return patterns.some(p => lower.includes(p.toLowerCase()));
}

/** Find the nearest front OSID with a given classification for movement. */
function findNearestFrontOsid(
    state: GameState,
    faction: FactionId,
    loc: Osid,
    adjacency: Map<Osid, Osid[]>,
    reverseMap: OperationalToCanonicalReverseMap,
    graphAnalysis: FactionGraphAnalysis,
    targetClassifications: string[]
): Osid | null {
    // BFS from current location through friendly territory toward front
    const controllerCache = new Map<Osid, FactionId | null>();
    const visited = new Set<Osid>([loc]);
    const queue: Array<{ osid: Osid; firstStep: Osid | null }> = [{ osid: loc, firstStep: null }];

    while (queue.length > 0) {
        const { osid, firstStep } = queue.shift()!;
        const neighbors = (adjacency.get(osid) ?? []).slice().sort(strictCompare);

        for (const n of neighbors) {
            if (visited.has(n)) continue;
            visited.add(n);

            let ctrl = controllerCache.get(n);
            if (ctrl === undefined) {
                ctrl = getPoliticalControllerOSID(state, n, reverseMap);
                controllerCache.set(n, ctrl);
            }
            if (ctrl !== faction) continue; // Only move through friendly territory

            const step = firstStep ?? n;
            const analysis = graphAnalysis.osid_analysis.get(n);
            if (analysis && targetClassifications.includes(analysis.classification)) {
                return step; // Return the FIRST step toward the target, not the target itself
            }
            queue.push({ osid: n, firstStep: step });
        }
    }
    return null;
}

/** BFS to find the nearest OSID matching a substring pattern through friendly territory.
 * Returns the FIRST STEP toward the target (for movement orders), not the target itself. */
function findNearestOsidByPattern(
    loc: Osid,
    pattern: string,
    faction: FactionId,
    adjacency: Map<Osid, Osid[]>,
    state: GameState,
    reverseMap: OperationalToCanonicalReverseMap
): Osid | null {
    const lowerPattern = pattern.toLowerCase();
    const visited = new Set<Osid>([loc]);
    const queue: Array<{ osid: Osid; firstStep: Osid }> = [];

    for (const n of (adjacency.get(loc) ?? []).slice().sort(strictCompare)) {
        if (visited.has(n)) continue;
        visited.add(n);
        const ctrl = getPoliticalControllerOSID(state, n, reverseMap);
        if (ctrl !== faction) continue;
        if (n.toLowerCase().includes(lowerPattern)) return n;
        queue.push({ osid: n, firstStep: n });
    }

    while (queue.length > 0) {
        const { osid, firstStep } = queue.shift()!;
        for (const n of (adjacency.get(osid) ?? []).slice().sort(strictCompare)) {
            if (visited.has(n)) continue;
            visited.add(n);
            const ctrl = getPoliticalControllerOSID(state, n, reverseMap);
            if (ctrl !== faction) continue;
            if (n.toLowerCase().includes(lowerPattern)) return firstStep;
            queue.push({ osid: n, firstStep });
        }
    }
    return null;
}

/** Minimum distance (BFS hops) from front for a brigade to use column march instead of 1-hop.
 * Lowered from 3→2: column march is more efficient than bumbling 1-hop-at-a-time because
 * it goes directly to a specific front OSID rather than just taking the nearest first step.
 * At 2 hops, column transit time ≈ 1 turn (same as 2× 1-hop), but with better targeting. */
const COLUMN_MARCH_MIN_HOPS = 2;

/**
 * Compute BFS hop distance from a location to the nearest front OSID.
 * Returns the number of hops, or Infinity if no front is reachable.
 */
function computeHopsToFront(
    loc: Osid,
    faction: FactionId,
    adjacency: Map<Osid, Osid[]>,
    state: GameState,
    reverseMap: OperationalToCanonicalReverseMap,
    graphAnalysis: FactionGraphAnalysis
): number {
    const visited = new Set<Osid>([loc]);
    const queue: Array<{ osid: Osid; depth: number }> = [{ osid: loc, depth: 0 }];

    while (queue.length > 0) {
        const { osid, depth } = queue.shift()!;
        const analysis = graphAnalysis.osid_analysis.get(osid);
        // Front = any OSID with enemy neighbors (not 'interior' or 'quiet' deep)
        if (depth > 0 && analysis && analysis.enemy_neighbors.length > 0) {
            return depth;
        }

        const neighbors = (adjacency.get(osid) ?? []).slice().sort(strictCompare);
        for (const n of neighbors) {
            if (visited.has(n)) continue;
            visited.add(n);
            const ctrl = getPoliticalControllerOSID(state, n, reverseMap);
            if (ctrl !== faction) continue;
            queue.push({ osid: n, depth: depth + 1 });
        }
    }
    return Infinity;
}

/**
 * Find the actual front-line destination OSID for a column march.
 * Unlike findNearestFrontOsid (which returns the FIRST HOP), this returns
 * the actual front OSID itself — the endpoint for multi-turn column transit.
 *
 * Prefers: undefended > critical > threatened (so reinforcements fill gaps).
 * Deterministic: BFS with sorted expansion.
 */
function findFrontDestinationForColumnMarch(
    state: GameState,
    faction: FactionId,
    loc: Osid,
    adjacency: Map<Osid, Osid[]>,
    reverseMap: OperationalToCanonicalReverseMap,
    graphAnalysis: FactionGraphAnalysis,
    assignedDests?: Map<Osid, number>
): Osid | null {
    // BFS outward through friendly territory, find closest front OSID
    // Priority: undefended first (needs reinforcement most), then critical, then threatened, then active
    // Distribution: skip destinations already assigned to ≥2 brigades (prevents stacking)
    const visited = new Set<Osid>([loc]);
    const queue: Array<{ osid: Osid; depth: number }> = [{ osid: loc, depth: 0 }];

    let bestTarget: Osid | null = null;
    let bestPriority = Infinity; // lower = better
    let bestDepth = Infinity;

    const classificationPriority: Record<string, number> = {
        undefended: 0,
        critical: 1,
        threatened: 2,
        active: 3
    };

    /** Max brigades that can march to the same front OSID. */
    const MAX_COLUMN_MARCH_PER_OSID = 2;

    while (queue.length > 0) {
        const { osid, depth } = queue.shift()!;

        // Early exit: if we've found a target and gone 2 BFS layers past it, stop
        // (allow some depth to find better-priority targets at similar distance)
        if (bestTarget && depth > bestDepth + 1) break;

        if (depth > 0) {
            const analysis = graphAnalysis.osid_analysis.get(osid);
            if (analysis && analysis.enemy_neighbors.length > 0) {
                // Distribution: skip if too many brigades already assigned here
                const assigned = assignedDests?.get(osid) ?? 0;
                if (assigned >= MAX_COLUMN_MARCH_PER_OSID) {
                    continue; // Don't expand past front, but skip this full OSID
                }

                const prio = classificationPriority[analysis.classification] ?? 10;
                if (prio < bestPriority || (prio === bestPriority && strictCompare(osid, bestTarget!) < 0)) {
                    bestTarget = osid;
                    bestPriority = prio;
                    bestDepth = depth;
                }
                continue; // Don't expand past front
            }
        }

        const neighbors = (adjacency.get(osid) ?? []).slice().sort(strictCompare);
        for (const n of neighbors) {
            if (visited.has(n)) continue;
            visited.add(n);
            const ctrl = getPoliticalControllerOSID(state, n, reverseMap);
            if (ctrl !== faction) continue;
            queue.push({ osid: n, depth: depth + 1 });
        }
    }

    // Update assignment tracker
    if (bestTarget && assignedDests) {
        assignedDests.set(bestTarget, (assignedDests.get(bestTarget) ?? 0) + 1);
    }

    return bestTarget;
}

/**
 * Shared interior-brigade movement: column march if deep, 1-hop move if close to front.
 * Returns true if an order was issued (caller should `continue`), false if nothing was done.
 */
/**
 * Shared interior-brigade movement: column march if deep, 1-hop move if close to front.
 * Returns true if an order was issued (caller should `continue`), false if nothing was done.
 *
 * Key fixes (n119):
 * - 1-hop classifications now include 'active' as fallback — brigades no longer get stuck
 *   when all front OSIDs are defended (was the primary cause of 53% RS brigades stuck in interior).
 * - Column march destination distribution via `columnAssignments` — prevents all interior
 *   brigades from converging on the same front OSID.
 */
function issueInteriorMovement(
    brigade: FormationState,
    loc: Osid,
    faction: FactionId,
    adjacency: Map<Osid, Osid[]>,
    state: GameState,
    reverseMap: OperationalToCanonicalReverseMap,
    graphAnalysis: FactionGraphAnalysis,
    result: OsidBotOrdersResult,
    oneHopClassifications: string[],
    columnAssignments?: Map<Osid, number>
): boolean {
    const hopsToFront = computeHopsToFront(loc, faction, adjacency, state, reverseMap, graphAnalysis);

    // Anti-oscillation: if brigade is only 1 hop from front but has been at this location
    // for multiple turns (entrenchment_turns > 0), use column march instead of 1-hop.
    // This prevents ping-pong between two equidistant positions.
    const useColumnMarch = hopsToFront >= COLUMN_MARCH_MIN_HOPS ||
        (hopsToFront === 1 && (brigade.entrenchment_turns ?? 0) >= 1);

    if (useColumnMarch) {
        const frontDest = findFrontDestinationForColumnMarch(state, faction, loc, adjacency, reverseMap, graphAnalysis, columnAssignments);
        if (frontDest) {
            result.column_march_orders[brigade.id] = frontDest;
            result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
            return true;
        }
    }
    // 1-hop movement: try priority classifications first, then fall back to any front OSID ('active')
    let dest = findNearestFrontOsid(state, faction, loc, adjacency, reverseMap, graphAnalysis, oneHopClassifications);
    if (!dest) {
        // Fallback: move toward ANY front OSID (including 'active' — already defended but still front)
        dest = findNearestFrontOsid(state, faction, loc, adjacency, reverseMap, graphAnalysis,
            ['undefended', 'critical', 'threatened', 'active', 'quiet']);
    }
    if (dest) result.movement_orders[brigade.id] = dest;
    result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
    return true;
}

// ═══════════════════════════════════════════════════════════════════════════
// Shared utilities
// ═══════════════════════════════════════════════════════════════════════════

/** Outcome ranking for threshold comparison. */
const OUTCOME_RANK: Record<PredictedOutcome, number> = {
    decisive_victory: 6,
    victory: 5,
    costly_victory: 4,
    stalemate: 3,
    repulsed: 2,
    catastrophic: 1
};

function isOutcomeSufficientForAttack(actual: PredictedOutcome, minimum: PredictedOutcome): boolean {
    return (OUTCOME_RANK[actual] ?? 0) >= (OUTCOME_RANK[minimum] ?? 0);
}

function isPartOfNamedOperation(state: GameState, formation: FormationState): boolean {
    if (!formation.corps_id || !state.corps_command) return false;
    const op = state.corps_command[formation.corps_id]?.active_operation;
    if (!op) return false;
    return op.phase === 'execution' && op.participating_brigades.includes(formation.id);
}

// ═══════════════════════════════════════════════════════════════════════════
// Main dispatcher — Directive-based brigade execution
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Supply connectivity: OSIDs reachable from faction supply (adequate or strained = on network).
 * Used for chokepoint/corridor defense priority. Derived from supply_state_by_osid (non-critical).
 */
export type SupplyConnectivityByFaction = Map<FactionId, Set<Osid>>;

/** Per-OSID ethnic composition (averaged from canonical settlements' 1991 census). */
export type OsidEthnicComposition = Map<string, { bosniak: number; serb: number; croat: number }>;

/**
 * Compute per-OSID ethnic composition by averaging canonical SID compositions.
 * Deterministic: iteration order does not matter (arithmetic average).
 */
export function computeOsidEthnicComposition(
    reverseMap: OperationalToCanonicalReverseMap,
    ethnicityData: SettlementEthnicityData
): OsidEthnicComposition {
    const result: OsidEthnicComposition = new Map();
    for (const [osid, canonicalSids] of reverseMap.entries()) {
        if (!canonicalSids || canonicalSids.length === 0) continue;
        let totalBosniak = 0, totalSerb = 0, totalCroat = 0, count = 0;
        for (const sid of canonicalSids) {
            const entry = ethnicityData.by_settlement_id[sid];
            if (!entry || !entry.composition) continue;
            totalBosniak += entry.composition.bosniak;
            totalSerb += entry.composition.serb;
            totalCroat += entry.composition.croat;
            count++;
        }
        if (count > 0) {
            result.set(osid, { bosniak: totalBosniak / count, serb: totalSerb / count, croat: totalCroat / count });
        }
    }
    return result;
}

/** Co-ethnic bonus: 0–80 proportional to co-ethnic share (full at ≥50%). */
function getCoEthnicScore(osid: Osid, faction: FactionId, ethnicMap: OsidEthnicComposition | undefined): number {
    if (!ethnicMap) return 0;
    const comp = ethnicMap.get(osid);
    if (!comp) return 0;
    let share: number;
    switch (faction) {
        case 'RS': share = comp.serb; break;
        case 'RBiH': share = comp.bosniak; break;
        case 'HRHB': share = comp.croat; break;
        default: return 0;
    }
    return Math.floor(Math.min(share / 0.5, 1.0) * 80);
}

/** Supply-aware attack penalty. Faction-specific conservatism. */
function getAttackerSupplyPenalty(attackerOsid: Osid, faction: FactionId, supplyReport?: SupplyStateByOsidReport | null): number {
    if (!supplyReport?.factions) return 0;
    const fac = supplyReport.factions.find(f => f.faction_id === faction);
    if (!fac?.by_osid) return 0;
    const entry = fac.by_osid.find(e => e.osid === attackerOsid);
    if (!entry) return 0;
    switch (entry.state) {
        case 'critical':
            if (faction === 'RBiH') return -300;
            if (faction === 'HRHB') return -250;
            return -200;
        case 'strained':
            if (faction === 'RBiH') return -100;
            if (faction === 'HRHB') return -75;
            return -50;
        default: return 0;
    }
}

/** Context needed for OSID bot decisions. Passed from the pipeline. */
export interface OsidBotContext {
    edges: EdgeRecord[];
    reverseMap: OperationalToCanonicalReverseMap;
    enemyZocByFaction: Map<FactionId, Set<Osid>>;
    supplyStateByOsid?: SupplyStateByOsidReport | null;
    supplyConnectivityByFaction?: SupplyConnectivityByFaction;
    ethnicCompositionByOsid?: OsidEthnicComposition;
}

// ═══════════════════════════════════════════════════════════════════════════
// Directive-based brigade execution (HoI-style: corps decides, brigade executes)
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Score a target OSID based on corps directive + tactical factors.
 * Strategic priorities come from the directive (offensive_targets, avoid_osids).
 * Tactical factors: combat prediction, co-ethnic bonus, supply, counter-attack.
 *
 * This replaces the three faction-specific scoring functions.
 * Faction personality is embedded in the corps directive (what targets, what thresholds).
 */
function scoreTargetFromDirective(
    osid: Osid,
    prediction: CombatPrediction,
    directive: import('../../state/game_state.js').CorpsDirective,
    faction: FactionId,
    ethnicMap?: OsidEthnicComposition
): number {
    let score = OUTCOME_SCORE[prediction.predicted_outcome] ?? 0;

    // Directive-driven: is this an offensive target?
    if (directive.offensive_targets.includes(osid)) {
        score += 200; // Corps wants this attacked
    }

    // Directive-driven: avoid zone
    if (directive.avoid_osids.includes(osid)) {
        score -= 500; // Corps forbids attacking here
    }

    // Tactical bonuses (same for all factions — universal combat logic)
    if (!prediction.defender_has_brigade) score += 100; // Undefended
    if (prediction.is_counter_attack_opportunity) score += 180; // Counter-attack
    if (prediction.defender_has_brigade && (prediction.defender_cohesion < 30 || prediction.defender_casualty_percent > 0.15)) {
        score += 80; // Weak defender
    }

    // Tactical penalties
    if (prediction.overextension_risk >= 3) score -= 150;
    if (prediction.attacker_casualty_percent > 0.20) score -= 150;
    if (prediction.overextension_risk >= 2) score -= 80;

    // Co-ethnic bonus (all factions fight harder for co-ethnic areas)
    score += getCoEthnicScore(osid, faction, ethnicMap);

    // Aggression modifier: flat bonus for offensive stances + multiplier for the whole score.
    // Flat component ensures stalemate targets (base 10) become viable when aggression is high.
    // Without this, a 1.3× multiplier on 10 only gives 13 — killed by any supply penalty.
    if (directive.aggression_modifier > 0) {
        score += Math.floor(directive.aggression_modifier * 120);
    }
    const aggressionMult = 1.0 + directive.aggression_modifier;
    score = Math.floor(score * aggressionMult);

    return score;
}

/**
 * Execute corps directive for all brigades of a faction.
 * Unified for all factions — faction personality comes from the directive.
 *
 * Brigade decision flow:
 * 1. ZoC-locked → retreat or attack ZoC source (tactical necessity)
 * 2. Hold OSID → DEFEND (corps says hold this position)
 * 3. Offensive target adjacent → evaluate attack using combat predictor
 * 4. Front coverage: fill gaps, spread along assigned front
 * 5. Interior: column march toward front
 * 6. Reserve: defend posture, ready to redeploy
 *
 * Deterministic: sorted brigade iteration, sorted target evaluation.
 */
function executeFactionDirectives(
    state: GameState,
    faction: FactionId,
    brigades: FormationState[],
    adjacency: Map<Osid, Osid[]>,
    reverseMap: OperationalToCanonicalReverseMap,
    terrainCache: Record<string, number>,
    enemyZoc: Set<Osid>,
    graphAnalysis: FactionGraphAnalysis,
    supplyStateByOsid?: SupplyStateByOsidReport | null,
    ethnicMap?: OsidEthnicComposition
): OsidBotOrdersResult {
    const result: OsidBotOrdersResult = { posture_orders: [], attack_orders: {}, movement_orders: {}, column_march_orders: {} };
    const chosenTargets = new Map<Osid, number>();
    const columnAssignments = new Map<Osid, number>();

    // Determine which brigades should be in reserve
    const corpsReserve = new Map<string, { total: number; reserved: number }>();
    for (const b of brigades) {
        if (!b.corps_id) continue;
        const existing = corpsReserve.get(b.corps_id) ?? { total: 0, reserved: 0 };
        existing.total++;
        corpsReserve.set(b.corps_id, existing);
    }

    // Alliance check for HRHB
    const isAlliedWithRBiH = areRbihHrhbAllied(state);

    for (const brigade of brigades) {
        const loc = brigade.location_osid!;
        const corpsId = brigade.corps_id;
        const cmd = corpsId ? state.corps_command?.[corpsId] : null;
        const directive = cmd?.directive ?? null;
        const corpsStance = cmd?.stance ?? 'balanced';
        const isLocked = isBrigadeInEnemyZoc(state, brigade.id, enemyZoc);
        const adjEnemy = getAdjacentEnemyOsids(loc, faction, adjacency, state, reverseMap);

        // Counter-attack eligibility: only this brigade may counter-attack the OSID it retreated from last turn.
        // Corps mates can provide concentration support, but cannot initiate.
        const retreatInfo = (brigade as { last_retreat_from?: { osid: string; turn: number } }).last_retreat_from;
        const counterAttackTarget: Osid | null = (retreatInfo && retreatInfo.turn === state.turn - 1)
            ? retreatInfo.osid as Osid : null;

        // --- Reserve check: should this brigade be in reserve? ---
        if (directive && corpsId) {
            const reserveInfo = corpsReserve.get(corpsId);
            if (reserveInfo) {
                const maxReserve = Math.floor(reserveInfo.total * directive.reserve_fraction);
                // Interior brigades (no enemy adjacent) become reserve first
                if (reserveInfo.reserved < maxReserve && adjEnemy.length === 0 && !isLocked) {
                    const osidAnalysis = graphAnalysis.osid_analysis.get(loc);
                    if (!osidAnalysis || osidAnalysis.enemy_neighbors.length === 0) {
                        reserveInfo.reserved++;
                        result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
                        continue;
                    }
                }
            }
        }

        // Default directive fallback — used by Rule 4 (defensive) and Rule 5 (offensive/balanced)
        const effectiveDirectiveDefault: import('../../state/game_state.js').CorpsDirective = {
            assigned_front_ids: [],
            offensive_targets: [],
            hold_osids: [],
            avoid_osids: [],
            max_attackers_per_target: 2,
            reserve_fraction: 0.2,
            min_attack_outcome: 'stalemate' as const,
            aggression_modifier: 0,
        };

        // --- Rule 1: ZoC-locked → retreat or attack ZoC source ---
        if (isLocked) {
            const retreatDests = getValidRetreatDestinations(state, brigade.id, adjacency, reverseMap, enemyZoc);
            if (retreatDests.length > 0) {
                result.movement_orders[brigade.id] = retreatDests[0]!;
            } else if (adjEnemy.length > 0) {
                result.posture_orders.push({ brigade_id: brigade.id, posture: 'attack' });
                result.attack_orders[brigade.id] = adjEnemy[0]!;
            }
            continue;
        }

        // --- Rule 2: Hold OSID → DEFEND (non-negotiable) ---
        if (directive && directive.hold_osids.includes(loc)) {
            // Counter-attack exception: if THIS brigade retreated from an adjacent OSID last turn, counter-attack
            if (counterAttackTarget && adjEnemy.includes(counterAttackTarget)) {
                const targets = predictAllAdjacentTargets(state, brigade.id, adjacency, reverseMap, terrainCache, 'attack', supplyStateByOsid);
                const counter = targets.find(t => t.osid === counterAttackTarget &&
                    isOutcomeSufficientForAttack(t.prediction.predicted_outcome, 'costly_victory'));
                if (counter && (chosenTargets.get(counter.osid) ?? 0) < (directive.max_attackers_per_target)) {
                    result.posture_orders.push({ brigade_id: brigade.id, posture: 'attack' });
                    result.attack_orders[brigade.id] = counter.osid;
                    chosenTargets.set(counter.osid, (chosenTargets.get(counter.osid) ?? 0) + 1);
                    continue;
                }
            }
            result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
            continue;
        }

        // --- Rule 3: Corps stance reorganize → rest ---
        if (corpsStance === 'reorganize') {
            result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
            continue;
        }

        // --- Rule 4: Defensive stance → defend, with retreat-based counter-attack only ---
        if (corpsStance === 'defensive') {
            // Only allow counter-attack if THIS brigade retreated from an adjacent OSID last turn
            if (counterAttackTarget && adjEnemy.includes(counterAttackTarget)) {
                const targets = predictAllAdjacentTargets(state, brigade.id, adjacency, reverseMap, terrainCache, 'attack', supplyStateByOsid);
                const effDir = directive ?? effectiveDirectiveDefault;
                const maxAtt = effDir.max_attackers_per_target;
                const counter = targets.find(t => t.osid === counterAttackTarget &&
                    (chosenTargets.get(t.osid) ?? 0) < maxAtt &&
                    isOutcomeSufficientForAttack(t.prediction.predicted_outcome, 'costly_victory'));
                if (counter) {
                    result.posture_orders.push({ brigade_id: brigade.id, posture: 'attack' });
                    result.attack_orders[brigade.id] = counter.osid;
                    chosenTargets.set(counter.osid, (chosenTargets.get(counter.osid) ?? 0) + 1);
                    continue;
                }
            }
            // Directive offensive target (rare during defensive but possible if corps has specific targets)
            if (adjEnemy.length > 0 && directive && directive.offensive_targets.length > 0) {
                const targets = predictAllAdjacentTargets(state, brigade.id, adjacency, reverseMap, terrainCache, 'attack', supplyStateByOsid);
                const maxAtt = directive.max_attackers_per_target;
                const viable = targets.find(t => {
                    if ((chosenTargets.get(t.osid) ?? 0) >= maxAtt) return false;
                    if (faction === 'HRHB' && isAlliedWithRBiH) {
                        const ctrl = getPoliticalControllerOSID(state, t.osid, reverseMap);
                        if (ctrl === 'RBiH') return false;
                    }
                    return directive.offensive_targets.includes(t.osid) &&
                        isOutcomeSufficientForAttack(t.prediction.predicted_outcome, directive.min_attack_outcome);
                });
                if (viable) {
                    result.posture_orders.push({ brigade_id: brigade.id, posture: 'attack' });
                    result.attack_orders[brigade.id] = viable.osid;
                    chosenTargets.set(viable.osid, (chosenTargets.get(viable.osid) ?? 0) + 1);
                    continue;
                }
            }
            // Fill adjacent front gaps even in defensive stance
            const defHere = countFactionBrigadesAtOsid(state, faction, loc);
            if (defHere >= 2) {
                const gap = findAdjacentFrontGap(state, loc, faction, adjacency, reverseMap, graphAnalysis);
                if (gap) {
                    result.movement_orders[brigade.id] = gap;
                    result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
                    continue;
                }
            }
            result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
            continue;
        }

        // --- Rule 5: Offensive/Balanced — evaluate attacks ---
        const effectiveDirective = directive ?? effectiveDirectiveDefault;
        if (adjEnemy.length > 0) {
            // HRHB alliance: don't attack RBiH when allied
            const filteredEnemy = (faction === 'HRHB' && isAlliedWithRBiH)
                ? adjEnemy.filter(o => getPoliticalControllerOSID(state, o, reverseMap) !== 'RBiH')
                : adjEnemy;

            if (filteredEnemy.length > 0) {
                const supplyPenalty = getAttackerSupplyPenalty(loc, faction, supplyStateByOsid);
                const targets = predictAllAdjacentTargets(state, brigade.id, adjacency, reverseMap, terrainCache, 'attack', supplyStateByOsid);

                // Filter targets: respect alliance, respect avoid_osids
                const validTargets = targets.filter(t => {
                    if (faction === 'HRHB' && isAlliedWithRBiH) {
                        const ctrl = getPoliticalControllerOSID(state, t.osid, reverseMap);
                        if (ctrl === 'RBiH') return false;
                    }
                    return true;
                });

                const scored = validTargets.map(t => ({
                    ...t,
                    finalScore: scoreTargetFromDirective(t.osid, t.prediction, effectiveDirective, faction, ethnicMap)
                        + supplyPenalty
                        + (counterAttackTarget === t.osid ? 180 : 0) // Retreat-based counter-attack bonus
                })).sort((a, b) => {
                    if (b.finalScore !== a.finalScore) return b.finalScore - a.finalScore;
                    return strictCompare(a.osid, b.osid);
                });

                const maxAtt = effectiveDirective.max_attackers_per_target;
                let bestTarget: typeof scored[0] | null = null;
                for (const s of scored) {
                    const existing = chosenTargets.get(s.osid) ?? 0;
                    if (existing >= maxAtt) continue;

                    // Pioneer: directive target with risky prediction — attack to seed concentration.
                    // Only for offensive/balanced corps stance (not defensive).
                    // Bypasses finalScore filter since repulsed outcomes have negative score.
                    if (existing === 0 && (corpsStance === 'offensive' || corpsStance === 'balanced') &&
                        effectiveDirective.offensive_targets.includes(s.osid) &&
                        isOutcomeSufficientForAttack(s.prediction.predicted_outcome, 'repulsed')) {
                        bestTarget = s;
                        break;
                    }
                    // Concentration: join an existing pioneer attack
                    if (existing > 0 && effectiveDirective.offensive_targets.includes(s.osid)) {
                        const combined = estimateConcentratedOutcome(s.prediction.power_ratio, existing);
                        if (combined && isOutcomeSufficientForAttack(combined, effectiveDirective.min_attack_outcome)) {
                            bestTarget = s;
                            break;
                        }
                    }

                    if (s.finalScore <= 0) continue;

                    // Check outcome threshold from directive
                    const outcomeOk = isOutcomeSufficientForAttack(s.prediction.predicted_outcome, effectiveDirective.min_attack_outcome);
                    // Counter-attack: this brigade retreated from this OSID last turn — relaxed threshold
                    const isRetreatCounter = (counterAttackTarget === s.osid);

                    if (outcomeOk || (isRetreatCounter && isOutcomeSufficientForAttack(s.prediction.predicted_outcome, 'stalemate'))) {
                        bestTarget = s;
                        break;
                    }
                    // Concentration: estimate combined outcome with co-attackers
                    if (existing > 0) {
                        const combined = estimateConcentratedOutcome(s.prediction.power_ratio, existing);
                        if (combined && isOutcomeSufficientForAttack(combined, effectiveDirective.min_attack_outcome)) {
                            bestTarget = s;
                            break;
                        }
                    }
                }

                if (bestTarget) {
                    result.posture_orders.push({ brigade_id: brigade.id, posture: 'attack' });
                    result.attack_orders[brigade.id] = bestTarget.osid;
                    chosenTargets.set(bestTarget.osid, (chosenTargets.get(bestTarget.osid) ?? 0) + 1);
                    continue;
                }
            }
        }

        // --- Rule 5b: Redeploy toward offensive target ---
        // On front but no offensive_target adjacent and there are excess brigades here:
        // Move along front toward the nearest offensive_target through friendly territory.
        if (adjEnemy.length > 0 && directive && directive.offensive_targets.length > 0 &&
            (corpsStance === 'offensive' || corpsStance === 'balanced')) {
            const hasAdjacentTarget = adjEnemy.some(o => directive.offensive_targets.includes(o));
            const factionHere = countFactionBrigadesAtOsid(state, faction, loc);
            if (!hasAdjacentTarget && factionHere >= 2) {
                // BFS through friendly territory toward nearest offensive_target neighbor
                const targetSet = new Set(directive.offensive_targets);
                const visited = new Set<Osid>([loc]);
                const queue: Array<{ osid: Osid; firstStep: Osid }> = [];
                for (const n of (adjacency.get(loc) ?? [])) {
                    const ctrl = getPoliticalControllerOSID(state, n, reverseMap);
                    if (ctrl === faction) {
                        visited.add(n);
                        queue.push({ osid: n, firstStep: n });
                    }
                }
                let redeployTarget: Osid | null = null;
                let maxHops = 6; // Don't search too far
                let idx = 0;
                while (idx < queue.length && maxHops > 0) {
                    const cur = queue[idx++]!;
                    // Check if this OSID is adjacent to an offensive_target
                    const neighbors = adjacency.get(cur.osid) ?? [];
                    const nearTarget = neighbors.some(n => targetSet.has(n));
                    if (nearTarget) {
                        redeployTarget = cur.firstStep;
                        break;
                    }
                    maxHops--;
                    for (const n of neighbors) {
                        if (visited.has(n)) continue;
                        const ctrl = getPoliticalControllerOSID(state, n, reverseMap);
                        if (ctrl === faction) {
                            visited.add(n);
                            queue.push({ osid: n, firstStep: cur.firstStep });
                        }
                    }
                }
                if (redeployTarget) {
                    result.movement_orders[brigade.id] = redeployTarget;
                    result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
                    continue;
                }
            }
        }

        // --- Rule 6: Front coverage — fill gaps, rebalance ---
        if (adjEnemy.length > 0) {
            // On front but no viable attack: fill adjacent gaps
            const factionHere = countFactionBrigadesAtOsid(state, faction, loc);
            if (factionHere >= 2) {
                const gap = findAdjacentFrontGap(state, loc, faction, adjacency, reverseMap, graphAnalysis);
                if (gap) {
                    result.movement_orders[brigade.id] = gap;
                    result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
                    continue;
                }
            }
            // Corps-level rebalancing
            const corpsCount = countCorpsBrigadesAtOsid(state, faction, brigade.corps_id, loc);
            if (corpsCount > MAX_CORPS_BRIGADES_PER_OSID) {
                issueInteriorMovement(brigade, loc, faction, adjacency, state, reverseMap, graphAnalysis, result,
                    ['undefended', 'critical', 'threatened'], columnAssignments);
                continue;
            }
            result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
            continue;
        }

        // --- Rule 7: Interior — move toward front, preferring offensive targets ---
        if (directive && directive.offensive_targets.length > 0) {
            // BFS through friendly territory toward nearest offensive_target neighbor
            const targetSet = new Set(directive.offensive_targets);
            const visited = new Set<Osid>([loc]);
            const queue: Array<{ osid: Osid; firstStep: Osid }> = [];
            for (const n of (adjacency.get(loc) ?? [])) {
                const ctrl = getPoliticalControllerOSID(state, n, reverseMap);
                if (ctrl === faction) {
                    visited.add(n);
                    queue.push({ osid: n, firstStep: n });
                }
            }
            let directiveTarget: Osid | null = null;
            let idx = 0;
            let maxSearch = 30;
            while (idx < queue.length && maxSearch > 0) {
                const cur = queue[idx++]!;
                const neighbors = adjacency.get(cur.osid) ?? [];
                if (neighbors.some(n => targetSet.has(n))) {
                    directiveTarget = cur.firstStep;
                    break;
                }
                maxSearch--;
                for (const n of neighbors) {
                    if (visited.has(n)) continue;
                    const ctrl = getPoliticalControllerOSID(state, n, reverseMap);
                    if (ctrl === faction) {
                        visited.add(n);
                        queue.push({ osid: n, firstStep: cur.firstStep });
                    }
                }
            }
            if (directiveTarget) {
                result.movement_orders[brigade.id] = directiveTarget;
                result.posture_orders.push({ brigade_id: brigade.id, posture: 'defend' });
                continue;
            }
        }
        // Fallback: standard interior movement toward nearest front
        issueInteriorMovement(brigade, loc, faction, adjacency, state, reverseMap, graphAnalysis, result,
            ['undefended', 'critical', 'threatened', 'active'], columnAssignments);
    }

    return result;
}

/**
 * Generate bot brigade orders for all bot factions using directive-based execution.
 *
 * Brigades read their corps directive (generated by generate-bot-corps-orders)
 * and execute: attack directive targets, hold positions, cover front, move to front.
 *
 * Replaces the three faction-specific AIs (VRS/ARBiH/HVO) with one unified executor.
 * Faction personality is expressed through the CorpsDirective (what targets, what thresholds).
 *
 * Deterministic: faction processing in sorted order, brigades sorted by ID.
 */
export function generateAllBotOrdersOsid(
    state: GameState,
    botFactions: FactionId[],
    ctx: OsidBotContext
): void {
    const adjacency = buildOsidAdjacency(ctx.edges);
    const terrainCache = buildTerrainCache(ctx.reverseMap);
    const sortedFactions = [...botFactions].sort(strictCompare);

    const allAttackOrders: Record<FormationId, Osid> = {};
    const allPostureOrders: Array<{ brigade_id: FormationId; posture: BrigadePosture }> = [];
    const allMovementOrders: Record<FormationId, Osid> = {};
    const allColumnMarchOrders: Record<FormationId, Osid> = {};

    for (const faction of sortedFactions) {
        const brigades = Object.values(state.formations ?? {})
            .filter((f): f is FormationState =>
                f != null &&
                f.faction === faction &&
                f.status === 'active' &&
                (f.kind === 'brigade' || f.kind === 'og' || f.kind === 'operational_group') &&
                f.location_osid != null
            )
            .sort((a, b) => strictCompare(a.id, b.id));

        if (brigades.length === 0) continue;

        const enemyZoc = ctx.enemyZocByFaction.get(faction) ?? new Set<Osid>();
        const graphAnalysis = analyzeFactionGraph(state, faction, adjacency, ctx.reverseMap);

        const result = executeFactionDirectives(
            state, faction, brigades, adjacency, ctx.reverseMap,
            terrainCache, enemyZoc, graphAnalysis,
            ctx.supplyStateByOsid, ctx.ethnicCompositionByOsid
        );

        // Accumulate results
        allPostureOrders.push(...result.posture_orders);
        for (const [bid, target] of Object.entries(result.attack_orders)) {
            if (target != null) allAttackOrders[bid as FormationId] = target;
        }
        for (const [bid, dest] of Object.entries(result.movement_orders)) {
            if (dest != null) allMovementOrders[bid as FormationId] = dest;
        }
        for (const [bid, dest] of Object.entries(result.column_march_orders)) {
            if (dest != null) allColumnMarchOrders[bid as FormationId] = dest;
        }
    }

    // Write to state
    if (!state.brigade_posture_orders) state.brigade_posture_orders = [];
    state.brigade_posture_orders.push(...allPostureOrders);

    if (Object.keys(allAttackOrders).length > 0) {
        state.brigade_attack_orders = allAttackOrders;
    }

    // Movement orders: merge regular moves + column march destinations
    const mergedMovement: Record<string, { destination_sids: string[] }> = {};
    for (const [bid, dest] of Object.entries(allMovementOrders)) {
        mergedMovement[bid] = { destination_sids: [dest] };
    }
    for (const [bid, dest] of Object.entries(allColumnMarchOrders)) {
        // Column march: write to movement orders (column movement processor handles multi-turn transit)
        mergedMovement[bid] = { destination_sids: [dest] };
    }
    if (Object.keys(mergedMovement).length > 0) {
        state.brigade_movement_orders = mergedMovement as Record<FormationId, { destination_sids: string[] }>;
    }
}
