import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

function read(path: string): string {
  return readFileSync(path, 'utf8');
}

describe('first-hour browser QA gate contract', () => {
  it('exposes an npm script for the non-destructive first-hour browser gate', () => {
    const packageJson = JSON.parse(read('package.json')) as { scripts?: Record<string, string> };

    expect(packageJson.scripts?.['qa:first-hour:browser']).toBe('node tools/ui/first_hour_browser_gate.cjs');
  });

  it('pins the requested first-hour browser invariants in the gate tool', () => {
    const tool = read('tools/ui/first_hour_browser_gate.cjs');

    expect(tool).toContain('.tmp_first_hour_browser_gate');
    expect(tool).toContain('consoleMessages');
    expect(tool).toContain('requestFailures');
    expect(tool).toContain('httpFailures');
    expect(tool).toContain('assertNoConsoleErrors');
    expect(tool).toContain('assertNoNetworkFailures');
    expect(tool).toContain("page.on('requestfailed'");
    expect(tool).toContain("page.on('response'");
    expect(tool).toContain('isIgnoredNetworkFailure');
    expect(tool).toContain('isIgnoredConsoleError');
    expect(tool).toContain('browserGatePhase');
    expect(tool).toContain("browserGatePhase === 'teardown'");
    expect(tool).toContain('deck: Failed to fetch');
    expect(tool).toContain('@deck__gl_layers');
    expect(tool).toContain('cleanBrowserGateOutputDir');
    expect(tool).toContain("fs.rmSync(SCREENSHOT_DIR");
    expect(tool).toContain('resolveBrowserGateEnv');
    expect(tool).toContain('WAR HAS STARTED');
    expect(tool).toContain('WAR BEGINS');
    expect(tool).toContain('President of the Presidency of the Republic of Bosnia and Herzegovina');
    expect(tool).toContain('What Is Bosnia?');
    expect(tool).toContain('deskBlockedWhileDecisionActive');
    expect(tool).toContain('Decision consequence records');
    expect(tool).toContain('War Chronicle');
    expect(tool).toContain('rawFirstHourLabelsAbsentByFaction');
    expect(tool).toContain('FORBIDDEN_FUTURE_KNOWLEDGE_PATTERNS');
    expect(tool).toContain('assertNoFirstHourKnowledgeLeaks');
    expect(tool).toContain('verifyFirstHourCodexKnowledgeBoundary(page, summary, flow)');
    expect(tool).toContain('verifyFirstHourDecisionRoomKnowledgeBoundary(page, summary, flow)');
    expect(tool).toContain('The Demilitarization of Srebrenica');
    expect(tool).toContain('The Vance-Owen Peace Plan');
    expect(tool).toContain('The Owen-Stoltenberg Plan');
    expect(tool).toContain('The Contact Group Plan');
    expect(tool).toContain('Karad');
    expect(tool).toContain('serverPortCleanupVerified');
    expect(tool).toContain('rbih_state_identity');
    expect(tool).toContain('turn_fired');
    expect(tool).toContain('response_id');
    expect(tool).toContain("responseId: 'civic'");
    expect(tool).toContain("responseId: 'all_six'");
    expect(tool).toContain("responseId: 'croat_republic'");
    expect(tool).toContain('clickByText(page, flow.responseLabel)');
    expect(tool).not.toContain('data-event-id="${flow.eventId}"');
    expect(tool).not.toContain('data-response-id="${flow.responseId}"');
    expect(tool).toContain('FACTION_OPENING_FLOWS');
    expect(tool).toContain("faction: 'RBiH'");
    expect(tool).toContain("faction: 'RS'");
    expect(tool).toContain("faction: 'HRHB'");
    expect(tool).toContain('main-menu-faction-${flow.faction}');
    expect(tool).toContain('assertToolbarRoutesDisabled');
    expect(tool).toContain('toolbarLockWhileDecisionActive');
    expect(tool).toContain('allFactionFoundationalFlows');
    expect(tool).toContain('rs_strategic_goals');
    expect(tool).toContain('hrhb_political_goal');
    expect(tool).toContain('The Assembly Speaks');
    expect(tool).toContain('What Is Herceg-Bosna?');
    expect(tool).toContain('verifyDecisionRecordsAndChronicle(page, summary, flow)');
    expect(tool).toContain('assertTurnZeroRecordsProvenanceCounts');
    expect(tool).toContain('turnZeroRecordsProvenanceCountsByFaction');
    expect(tool).toContain('records-subtab-${id}');
    expect(tool).toContain('receiptChecksByFaction');
    expect(tool).toContain('futureKnowledgeLeaksAbsentByFaction');
    expect(tool).not.toContain('receiptCheck: false');
    expect(tool).not.toContain('verifyRbihRecordsAndChronicle');
  });
});

describe('live surface browser sweep contract', () => {
  it('exposes an npm script for the non-destructive live surface browser sweep', () => {
    const packageJson = JSON.parse(read('package.json')) as { scripts?: Record<string, string> };

    expect(packageJson.scripts?.['qa:live-surface:browser']).toBe('node tools/ui/live_surface_browser_sweep.cjs');
  });

  it('pins the requested live surface browser invariants in the sweep tool', () => {
    const tool = read('tools/ui/live_surface_browser_sweep.cjs');

    expect(tool).toContain('.tmp_live_surface_browser_sweep');
    expect(tool).toContain('consoleMessages');
    expect(tool).toContain('requestFailures');
    expect(tool).toContain('httpFailures');
    expect(tool).toContain('assertNoConsoleErrors');
    expect(tool).toContain('assertNoNetworkFailures');
    expect(tool).toContain("page.on('requestfailed'");
    expect(tool).toContain("page.on('response'");
    expect(tool).toContain('isIgnoredNetworkFailure');
    expect(tool).toContain('isIgnoredConsoleError');
    expect(tool).toContain('browserGatePhase');
    expect(tool).toContain("browserGatePhase === 'teardown'");
    expect(tool).toContain('deck: Failed to fetch');
    expect(tool).toContain('@deck__gl_layers');
    expect(tool).toContain('cleanBrowserGateOutputDir');
    expect(tool).toContain("fs.rmSync(SCREENSHOT_DIR");
    expect(tool).toContain('resolveBrowserGateEnv');
    expect(tool).toContain('WAR HAS STARTED');
    expect(tool).toContain('WAR BEGINS');
    expect(tool).toContain('Civic multi-ethnic republic');
    expect(tool).toContain('LIVE_SURFACES');
    expect(tool).toContain('Desk');
    expect(tool).toContain('War Map');
    expect(tool).toContain('Army HQ');
    expect(tool).toContain('Records');
    expect(tool).toContain('Chronicle');
    expect(tool).toContain('Codex');
    expect(tool).toContain('Latest Filed Decision');
    expect(tool).toContain('data-testid="codex-panel"');
    expect(tool).toContain('assertSingleShellSurface');
    expect(tool).toContain('assertNoRawTechnicalTokens');
    expect(tool).toContain('FORBIDDEN_FUTURE_KNOWLEDGE_PATTERNS');
    expect(tool).toContain('assertNoFutureKnowledgeLeaks');
    expect(tool).toContain('The Demilitarization of Srebrenica');
    expect(tool).toContain('The Vance-Owen Peace Plan');
    expect(tool).toContain('The Owen-Stoltenberg Plan');
    expect(tool).toContain('The Contact Group Plan');
    expect(tool).toContain("label: 'OSID'");
    expect(tool).toContain("label: 'ATK'");
    expect(tool).toContain("label: 'raw planning ids'");
    expect(tool).toContain('runOwnerJourneyDrilldown');
    expect(tool).toContain('ownerJourneyDrilldown');
    expect(tool).toContain('runArmyHqInternalDrilldown');
    expect(tool).toContain('armyHqInternalDrilldown');
    expect(tool).toContain('army_hq_internal_summary');
    expect(tool).toContain('army_hq_internal_personnel');
    expect(tool).toContain('army_hq_internal_corps_card');
    expect(tool).toContain('army-hq-opening-command-provenance');
    expect(tool).toContain('data-commander-source="opening_read_model"');
    expect(tool).toContain('runArmyHqPersonnelBrigadeLiveProof');
    expect(tool).toContain('armyHqPersonnelBrigadeLiveProof');
    expect(tool).toContain('personnel-orbat-brigade-link');
    expect(tool).toContain('runArmyHqSectorFrontSegmentLiveProof');
    expect(tool).toContain('armyHqSectorFrontSegmentLiveProof');
    expect(tool).toContain('army-hq-sector-frontage');
    expect(tool).toContain('army-hq-sector-inspect');
    expect(tool).toContain('army-hq-sector-brigade-inspect');
    expect(tool).toContain('army_hq_sector_brigade_inspect_on_field_live_proof');
    expect(tool).toContain('armyHqSectorBrigadeInspectOnFieldLiveProof');
    expect(tool).toContain('army_hq_sector_inspect_on_field_live_proof');
    expect(tool).toContain('armyHqSectorInspectOnFieldLiveProof');
    expect(tool).toContain('runMapContextMenuLiveProof');
    expect(tool).toContain('mapContextMenuLiveProof');
    expect(tool).toContain('map_context_menu_live_proof');
    expect(tool).toContain('map_context_menu_action_live_proof');
    expect(tool).toContain('map-context-menu-action-');
    expect(tool).toContain('map-context-menu-action-deselect');
    expect(tool).toContain('dom-contextmenu');
    expect(tool).toContain('dev-seam');
    expect(tool).toContain('runRecordsAarFormationLinkLiveProof');
    expect(tool).toContain('recordsAarFormationLinkLiveProof');
    expect(tool).toContain('runBattleMarkerLiveProof');
    expect(tool).toContain('battleMarkerLiveProof');
    expect(tool).toContain('battle_marker_live_proof');
    expect(tool).toContain('battleMarkerOsids');
    expect(tool).toContain('buildRecordsAarLiveProofFixtureState');
    expect(tool).toContain('apr_1992_initial_save.json');
    expect(tool).toContain("op:gradacac:donja_tramosnica_2");
    expect(tool).toContain("arbih_213th_vitezka_mountain");
    expect(tool).toContain("rs_1st_birac");
    expect(tool).toContain('loadRecordsAarLiveProofFixture');
    expect(tool).toContain('handleManualSaveLoad');
    expect(tool).toContain('fixtureBattleSelector');
    expect(tool).toContain('fixtureAttackerLinkSelector');
    expect(tool).toContain('clickedFormationId');
    expect(tool).not.toContain('skipped:no-visible-aar-battle-row');
    expect(tool).not.toContain('skipped:no-visible-aar-formation-link');
    expect(tool.indexOf('await runArchiveInboxDrilldown(page, summary);')).toBeLessThan(
      tool.indexOf('await loadOperationOpportunityLiveProofFixture(page, summary);'),
    );
    expect(tool.indexOf('await runCodexInternalDrilldown(page, summary);')).toBeLessThan(
      tool.indexOf('await loadOperationOpportunityLiveProofFixture(page, summary);'),
    );
    expect(tool.indexOf('await loadOperationOpportunityLiveProofFixture(page, summary);')).toBeLessThan(
      tool.indexOf('await runPresidentialInboxRoutingLiveProof(page, summary);'),
    );
    expect(tool.indexOf('await runPresidentialInboxRoutingLiveProof(page, summary);')).toBeLessThan(
      tool.indexOf('await loadRecordsAarLiveProofFixture(page, summary);'),
    );
    expect(tool.indexOf('await runCodexInternalDrilldown(page, summary);')).toBeLessThan(
      tool.indexOf('await loadRecordsAarLiveProofFixture(page, summary);'),
    );
    expect(tool.indexOf('await loadRecordsAarLiveProofFixture(page, summary);')).toBeLessThan(
      tool.indexOf('await runRecordsAarFormationLinkLiveProof(page, summary);'),
    );
    expect(tool).toContain('aar-battle-row');
    expect(tool).toContain('aar-formation-link');
    expect(tool).toContain('runArchiveInboxDrilldown');
    expect(tool).toContain('archiveChronicleToRecordsDrilldown');
    expect(tool).toContain('archiveRecordsDecisionToChronicleDrilldown');
    expect(tool).toContain('presidentialInboxVisible');
    expect(tool).toContain('runPresidentialInboxRoutingLiveProof');
    expect(tool).toContain('presidentialInboxRoutingLiveProof');
    expect(tool).toContain('presidentialInboxRoutingLiveProof: false');
    expect(tool).toContain('buildOperationOpportunityLiveProofFixtureState');
    expect(tool).toContain('loadOperationOpportunityLiveProofFixture');
    expect(tool).toContain('operation_opportunities');
    expect(tool).toContain('live_window');
    expect(tool).toContain('data-inbox-action="decision_room"');
    expect(tool).toContain('data-inbox-item-type="operation_opportunity"');
    expect(tool).toContain('desk-card-operation_opportunity');
    expect(tool).toContain('desk-card-action');
    expect(tool).toContain('warroom-decision-room-host');
    expect(tool).toContain('presidential-decision-room');
    expect(tool).toContain('decision-room-priority-card-opportunity:${OPPORTUNITY_LIVE_FIXTURE_ID}');
    expect(tool).toContain('inbox_routing_decision_room');
    expect(tool).toContain('inbox_routing_desk_card_operation_opportunity');
    expect(tool).toContain('runOperationOpportunityLedgerLiveProof');
    expect(tool).toContain('operationOpportunityLedgerLiveProof');
    expect(tool).toContain('operation_opportunity_ledger_live_proof');
    expect(tool).toContain('opportunity-ledger-record');
    expect(tool).toContain('data-proposal-id="${OPPORTUNITY_LIVE_FIXTURE_ID}"');
    expect(tool).toContain('deskRecordsRoute');
    expect(tool).toContain('chronicle-open-record');
    expect(tool).toContain("chronicleRecordTarget === 'decision'");
    expect(tool).toContain('records-content');
    expect(tool).toContain('decision-consequence-open-chronicle');
    expect(tool).toContain('data-focused-chronicle-decision-record-id');
    expect(tool).toContain('archiveRecordsDecisionToChronicleRecordId');
    expect(tool).not.toContain('skipped:no-chronicle-target');
    expect(tool).toContain('presidential-inbox');
    expect(tool).toContain('president-desk-shell');
    expect(tool).toContain('desk-consequence-open-records');
    expect(tool).toContain('runCodexInternalDrilldown');
    expect(tool).toContain('codexInternalDrilldown');
    expect(tool).toContain('codexInternalDrilldown: false');
    expect(tool).toContain('await runCodexInternalDrilldown(page, summary);');
    expect(tool).toContain('codex_internal_selected_essay');
    expect(tool).toContain('codex-essay-row');
    expect(tool).toContain('codex-selected-essay');
    expect(tool).toContain('codex-selected-essay-body');
    expect(tool).toContain('activateVisibleControl');
    expect(tool).toContain('clickFirstSectorWithVisibleFormation');
    expect(tool).toContain('No visible Corps Front brigade rows with settlement locations found after inspecting');
    expect(tool).toContain('owner_journey_decision_room');
    expect(tool).toContain('owner_journey_sector_overview');
    expect(tool).toContain('owner_journey_formation_detail');
    expect(tool).toContain('owner_journey_ops_planning_modal');
    expect(tool).toContain('owner_journey_formation_location_context');
    expect(tool).toContain("visibleDetailPanels.length === 1");
    expect(tool).toContain('owner_journey_records_tabs');
    expect(tool).toContain('ownerJourneyDrilldownByFaction');
    expect(tool).toContain('ownerJourneyOpsPlanningModalByFaction');
    expect(tool).toContain("await loadPlayerFactionStartupFixture(page, summary, 'RS');");
    expect(tool).toContain("await runOwnerJourneyDrilldown(page, summary, 'RS');");
    expect(tool).toContain("const evidenceId = (id) => (journeyKey === 'rbih' ? id : `${journeyKey}_${id}`);");
    expect(tool).toContain('runTurnZeroSetupProvenanceLiveProof');
    expect(tool).toContain('turnZeroSetupProvenanceLiveProof');
    expect(tool).toContain('command-card-cat_record"][data-awwv-count="0"][data-awwv-urgent-count="0"]');
    expect(tool).toContain('warroom-toolbar-command-surface');
    expect(tool).toContain('toolbar-route-desk');
    expect(tool).toContain('toolbar-route-war-map');
    expect(tool).toContain('[data-testid="tactical-map"]');
    expect(tool).not.toContain('main[aria-label^="Tactical map"]');
    expect(tool).toContain('toolbar-route-records');
    expect(tool).toContain('data-testid="codex-close"');
    expect(tool).toContain('data-testid="command-card-strip-close"');
    expect(tool).toContain('data-testid="warroom-decision-room-close"');
    expect(tool).toContain('data-testid="command-card-cat_war_direction"');
    expect(tool).toContain('data-testid="oob-section-sectors-toggle"');
    expect(tool).toContain('data-testid="oob-sector-row"');
    expect(tool).toContain('data-coverage-tier');
    expect(tool).toContain('data-current-brigade-count');
    expect(tool).toContain('data-command-directed-brigade-count');
    expect(tool).toContain('data-testid="corps-front-brigade-row"');
    expect(tool).toContain('data-testid="corps-front-draft-directive"');
    expect(tool).toContain('data-testid="ops-planning-modal"');
    expect(tool).toContain('data-testid="ops-planning-phase-panel"');
    expect(tool).toContain('data-location-osid');
    expect(tool).toContain('data-testid="formation-detail-panel"');
    expect(tool).toContain('data-testid="formation-location-link"');
    expect(tool).toContain('records-subtab-');
    expect(tool).toContain('records-subtab-aftermath');
    expect(tool).toContain('records-subtab-aar');
    expect(tool).toContain('data-selected="true"');
    expect(tool).toContain('convoy_decision');
    expect(tool).toContain('Expires T');
    expect(tool).toContain('op:');
    expect(tool).toContain('.json');
    expect(tool).toContain('waitForPortClosed');
  });

  it('pins live-owner journey selector hooks in the map UI', () => {
    expect(read('src/ui/map/components/MainMenu.tsx')).toContain('data-testid={`main-menu-faction-${faction}`}');
    expect(read('src/ui/map/components/SidePickerOverlay.tsx')).toContain('data-testid={`side-picker-faction-${faction}`}');
    expect(read('src/ui/map/components/PresidentialToolbar.tsx')).toContain('data-testid="toolbar-route-desk"');
    expect(read('src/ui/map/components/PresidentialToolbar.tsx')).toContain('data-testid="toolbar-route-war-map"');
    expect(read('src/ui/map/components/PresidentialToolbar.tsx')).toContain('data-testid="toolbar-route-records"');
    expect(read('src/ui/map/map/MapContainer.tsx')).toContain('data-testid="tactical-map"');
    expect(read('src/ui/map/map/MapContainer.tsx')).toContain('VITE_AWWV_DISABLE_PMTILES');
    expect(read('src/ui/map/map/MapContainer.tsx')).toContain("disable_pmtiles') === '1'");
    expect(read('src/ui/map/map/MapContainer.tsx')).toContain('stripPmtilesSourcesForCiFallback');
    expect(read('src/ui/map/components/CodexPanel.tsx')).toContain('data-testid="codex-close"');
    expect(read('src/ui/map/components/CodexPanel.tsx')).toContain('data-testid="codex-essay-row"');
    expect(read('src/ui/map/components/CodexPanel.tsx')).toContain('data-essay-id={essay.id}');
    expect(read('src/ui/map/components/CodexPanel.tsx')).toContain("data-selected={isSelected ? 'true' : 'false'}");
    expect(read('src/ui/map/components/CodexPanel.tsx')).toContain('data-testid="codex-selected-essay"');
    expect(read('src/ui/map/components/CodexPanel.tsx')).toContain('data-testid="codex-selected-essay-body"');
    expect(read('src/ui/map/components/warroom/CommandCardStrip.tsx')).toContain('data-testid="command-card-strip-close"');
    expect(read('src/ui/map/App.tsx')).toContain('data-testid="warroom-decision-room-close"');
    expect(read('src/ui/map/components/OOBSidebar.tsx')).toContain('testId="oob-section-sectors-toggle"');
    expect(read('src/ui/map/components/OOBSidebar.tsx')).toContain('data-coverage-tier={coverageTier}');
    expect(read('src/ui/map/components/OOBSidebar.tsx')).toContain('data-current-brigade-count={sectorAssignment.allCurrentIds.length}');
    expect(read('src/ui/map/components/CorpsDetail.tsx')).toContain('data-testid="corps-detail-sector-row"');
    expect(read('src/ui/map/components/CorpsDetail.tsx')).toContain('data-coverage-tier={coverageTier}');
    expect(read('src/ui/map/components/CorpsFrontPanel.tsx')).toContain('data-testid="corps-front-draft-directive"');
    expect(read('src/ui/map/components/ops_modal/OpsPlanningModal.tsx')).toContain('data-testid="ops-planning-modal"');
    expect(read('src/ui/map/components/ops_modal/OpsPlanningModal.tsx')).toContain('data-testid="ops-planning-phase-panel"');
    expect(read('src/ui/map/components/OOBSidebar.tsx')).toContain('data-testid="oob-sector-row"');
    expect(read('src/ui/map/components/OOBSidebar.tsx')).toContain('data-selected={selectedCorpsFrontSectorId === sector.sector_id');
    expect(read('src/ui/map/components/CorpsFrontPanel.tsx')).toContain('data-testid="corps-front-brigade-row"');
    expect(read('src/ui/map/components/CorpsFrontPanel.tsx')).toContain('data-formation-id={f.id}');
    expect(read('src/ui/map/components/CorpsFrontPanel.tsx')).toContain('data-location-osid={f.location_osid ?? undefined}');
    expect(read('src/ui/map/components/FormationDetail.tsx')).toContain('data-testid="formation-detail-panel"');
    expect(read('src/ui/map/components/FormationDetail.tsx')).toContain('idPrefix="formation-detail"');
    expect(read('src/ui/map/components/FormationDetail.tsx')).toContain('data-testid="formation-location-link"');
    expect(read('src/ui/map/components/FormationDetail.tsx')).toContain("kind: 'field-formation-at-settlement'");
    expect(read('src/ui/map/components/army_hq/RecordsContent.tsx')).toContain('data-testid={`records-subtab-${id}`}');
    expect(read('src/ui/map/components/army_hq/RecordsContent.tsx')).toContain("data-selected={subTab === id ? 'true' : 'false'}");
    expect(read('src/ui/map/components/army_hq/RecordsContent.tsx')).toContain('data-testid="records-content"');
    expect(read('src/ui/map/components/army_hq/RecordsContent.tsx')).toContain('data-testid="records-archive-summary"');
    expect(read('src/ui/map/components/army_hq/DecisionConsequenceRecordsPanel.tsx')).toContain('data-testid="decision-consequence-records-panel"');
    expect(read('src/ui/map/components/army_hq/DecisionConsequenceRecordsPanel.tsx')).toContain('data-testid="decision-consequence-record"');
    expect(read('src/ui/map/components/army_hq/DecisionConsequenceRecordsPanel.tsx')).toContain('data-record-target={record.recordTarget}');
    expect(read('src/ui/map/components/army_hq/DecisionConsequenceRecordsPanel.tsx')).toContain('data-testid="decision-consequence-open-chronicle"');
    expect(read('src/ui/map/components/EventDecisionModal.tsx')).toContain('data-testid="event-decision-response"');
    expect(read('src/ui/map/components/EventDecisionModal.tsx')).not.toContain('data-event-id={decision.event_id}');
    expect(read('src/ui/map/components/EventDecisionModal.tsx')).not.toContain('data-response-id={option.id}');
    expect(read('src/ui/map/components/army_hq/OpportunityLedgerPanel.tsx')).toContain('data-testid="opportunity-ledger-record"');
    expect(read('src/ui/map/components/army_hq/OpportunityLedgerPanel.tsx')).toContain('data-proposal-id={record.proposal_id}');
    expect(read('src/ui/map/components/army_hq/OpportunityLedgerPanel.tsx')).toContain('data-status={record.status}');
    expect(read('src/ui/map/components/chronicle/ChronicleOverlay.tsx')).toContain('data-testid="chronicle-overlay"');
    expect(read('src/ui/map/components/chronicle/ChronicleOverlay.tsx')).toContain('data-testid="chronicle-close"');
    expect(read('src/ui/map/components/chronicle/ChronicleOverlay.tsx')).toContain('data-testid={`chronicle-filter-${filter.id}`}');
    expect(read('src/ui/map/components/chronicle/ChronicleOverlay.tsx')).toContain('data-testid="chronicle-dossier-entry"');
    expect(read('src/ui/map/components/chronicle/ChronicleOverlay.tsx')).toContain('data-testid="chronicle-open-record"');
    expect(read('src/ui/map/components/chronicle/ChronicleOverlay.tsx')).toContain('data-decision-record-id={entry.metadata?.decisionRecordId ?? undefined}');
    expect(read('src/ui/map/i18n/messages.en.ts')).toContain("'chronicle.openDecisionRecord': 'Focus Chronicle Decision'");
    expect(read('src/ui/map/components/PresidentialInbox.tsx')).toContain('data-testid="presidential-inbox"');
    expect(read('src/ui/map/components/PresidentialInbox.tsx')).toContain('data-testid="presidential-inbox-card"');
    expect(read('src/ui/map/components/PresidentialInbox.tsx')).toContain("onAction('decision_room', 'opening-brief:desk')");
    expect(read('src/ui/map/components/PresidentialInbox.tsx')).toContain('data-inbox-action={item.action}');
    expect(read('src/ui/map/components/presidential_desk/PresidentDeskShell.tsx')).toContain('data-testid="president-desk-shell"');
    expect(read('src/ui/map/components/presidential_desk/PresidentDeskShell.tsx')).not.toContain('data-testid="desk-action-records"');
    expect(read('src/ui/map/components/presidential_desk/PresidentDeskShell.tsx')).not.toContain('data-testid="desk-action-war-map"');
    expect(read('src/ui/map/components/presidential_desk/PresidentDeskShell.tsx')).not.toContain('data-testid="desk-open-command-surface"');
    expect(read('src/ui/map/components/presidential_desk/ConsequenceStrip.tsx')).toContain('data-testid="desk-consequence-open-records"');
    expect(read('src/ui/map/components/army_hq/ArmyHQCorpsCard.tsx')).toContain('data-testid="army-hq-corps-card"');
    expect(read('src/ui/map/components/army_hq/ArmyHQCorpsCard.tsx')).toContain('data-testid="army-hq-corps-card-detail"');
    expect(read('src/ui/map/components/army_hq/ArmyHQCorpsCard.tsx')).toContain('data-commander-source={data.commanderDisplay?.source ?? \'none\'}');
    expect(read('src/ui/map/components/army_hq/ArmyHQCorpsCard.tsx')).toContain('data-testid="army-hq-opening-command-provenance"');
    expect(read('src/ui/map/components/army_hq/ArmyHQCorpsCard.tsx')).toContain("t('commanderDisplay.openingCommand')");
    expect(read('src/ui/map/components/army_hq/PersonnelContent.tsx')).toContain('data-testid="personnel-orbat-brigade-link"');
    expect(read('src/ui/map/components/army_hq/PersonnelContent.tsx')).toContain('data-command-id={command.id}');
    expect(read('src/ui/map/components/army_hq/PersonnelContent.tsx')).toContain('data-command-kind={command.kind}');
    expect(read('src/ui/map/components/army_hq/PersonnelContent.tsx')).toContain('data-formation-id={b.id}');
    expect(read('src/ui/map/components/army_hq/SectorsSection.tsx')).toContain('data-testid="army-hq-sector-row"');
    expect(read('src/ui/map/components/army_hq/SectorsSection.tsx')).toContain('data-testid="army-hq-sector-frontage"');
    expect(read('src/ui/map/components/army_hq/SectorsSection.tsx')).toContain('data-testid="army-hq-sector-inspect"');
    expect(read('src/ui/map/components/army_hq/SectorsSection.tsx')).toContain('data-testid="army-hq-sector-brigade-inspect"');
    expect(read('src/ui/map/components/army_hq/SectorsSection.tsx')).toContain('data-sector-id={sector.sector_id}');
    expect(read('src/ui/map/components/army_hq/SectorsSection.tsx')).toContain('data-corps-id={corpsId}');
    expect(read('src/ui/map/components/army_hq/SectorsSection.tsx')).toContain('data-front-segments={sector.length_edges}');
    expect(read('src/ui/map/components/army_hq/OperationsSection.tsx')).toContain('data-testid="army-hq-operation-brigade-inspect"');
    expect(read('src/ui/map/components/army_hq/OrbatSection.tsx')).toContain('data-testid="army-hq-formation-inspect"');
    expect(read('src/ui/map/components/army_hq/OrbatSection.tsx')).toContain('data-formation-id={b.id}');
    expect(read('src/ui/map/components/army_hq/OrbatSection.tsx')).toContain('data-corps-id={corpsId}');
    expect(read('src/ui/map/components/AARPanel.tsx')).toContain('data-testid="aar-battle-row"');
    expect(read('src/ui/map/components/AARPanel.tsx')).toContain('data-testid="aar-formation-link"');
  });
});

describe('browser QA CI wiring contract', () => {
  it('runs browser gates for packaged runtime data and asset path changes', () => {
    const detector = read('.github/scripts/detect-full-suite-changes.sh');

    expect(detector).toContain('"data/derived/"');
    expect(detector).toContain('"data/ui/"');
    expect(detector).toContain('"data/scenarios/"');
    expect(detector).toContain('"assets/"');
    expect(detector).toContain('"build/icon.png"');
  });

  it('runs the self-scanning player-experience gate in the required full-suite job', () => {
    const workflow = read('.github/workflows/full-suite-and-fingerprint.yml');

    const fullSuiteJobStart = workflow.indexOf('  full-suite:');
    const structuralFingerprintStart = workflow.indexOf('  structural-fingerprint:');
    const fullSuiteJob = workflow.slice(fullSuiteJobStart, structuralFingerprintStart);
    expect(fullSuiteJob).not.toContain('lfs: true');
    expect(read('.github/workflows/README.md')).toContain('does not eager-fetch Git LFS before path');
    expect(fullSuiteJob).toContain('timeout-minutes: 75');
    expect(workflow).toContain('name: Player experience gate');
    expect(workflow).toContain('run: npm run qa:player-experience');
    expect(workflow).not.toContain('run: npm run qa:first-hour:browser');
    expect(workflow).not.toContain('run: npm run qa:live-surface:browser');
    expect(workflow).toContain('name: Install Puppeteer Chrome for browser gates');
    expect(workflow).toContain('run: npx puppeteer browsers install chrome');
    expect(read('tools/ui/browser_gate_pmtiles_env.cjs')).toContain('VITE_AWWV_DISABLE_PMTILES');
    expect(read('tools/ui/browser_gate_pmtiles_env.cjs')).toContain('version https://git-lfs.github.com/spec/v1');

    const fullSuiteStart = workflow.indexOf('name: Full vitest suite');
    const chromeInstallStart = workflow.indexOf('name: Install Puppeteer Chrome for browser gates');
    const playerExperienceStart = workflow.indexOf('name: Player experience gate');
    const skippedStart = workflow.indexOf('name: No relevant changes');
    expect(chromeInstallStart).toBeGreaterThan(fullSuiteStart);
    expect(playerExperienceStart).toBeGreaterThan(chromeInstallStart);
    expect(skippedStart).toBeGreaterThan(playerExperienceStart);

    const chromeInstallBlock = workflow.slice(chromeInstallStart, playerExperienceStart);
    const playerExperienceBlock = workflow.slice(playerExperienceStart, skippedStart);
    expect(chromeInstallBlock).toContain("if: steps.changes.outputs.relevant == 'true'");
    expect(playerExperienceBlock).toContain("if: steps.changes.outputs.relevant == 'true'");
  });
});
