import type { FormationView } from '../data/types';

/**
 * Mock formations with corps_id for OOB sidebar / CorpsCard / BrigadeRow stories.
 */
export const mockOobFormations: FormationView[] = [
  {
    id: 'rs_brig_1',
    faction: 'RS',
    name: '1st Krajina Brigade',
    kind: 'brigade',
    readiness: 'active',
    cohesion: 78,
    fatigue: 12,
    status: 'assigned',
    createdTurn: 1,
    tags: [],
    location_osid: 'op:banja_luka',
    personnel: 2800,
    corps_id: 'rs_corps_north',
  },
  {
    id: 'rs_brig_2',
    faction: 'RS',
    name: '2nd Krajina Brigade',
    kind: 'brigade',
    readiness: 'active',
    cohesion: 65,
    fatigue: 22,
    status: 'reserve',
    createdTurn: 2,
    tags: [],
    location_osid: 'op:prijedor',
    personnel: 2100,
    corps_id: 'rs_corps_north',
  },
  {
    id: 'rs_brig_3',
    faction: 'RS',
    name: '3rd Romanija Brigade',
    kind: 'brigade',
    readiness: 'active',
    cohesion: 66,
    fatigue: 24,
    status: 'in-combat',
    createdTurn: 1,
    tags: [],
    location_osid: 'op:pale',
    personnel: 2100,
    corps_id: 'rs_corps_east',
  },
  {
    id: 'rbih_brig_1',
    faction: 'RBiH',
    name: '1st Sarajevo Brigade',
    kind: 'brigade',
    readiness: 'active',
    cohesion: 72,
    fatigue: 18,
    status: 'assigned',
    createdTurn: 2,
    tags: [],
    location_osid: 'op:sarajevo',
    personnel: 2400,
    corps_id: 'rbih_corps_sarajevo',
  },
  {
    id: 'rbih_brig_2',
    faction: 'RBiH',
    name: '2nd Sarajevo Brigade',
    kind: 'brigade',
    readiness: 'active',
    cohesion: 58,
    fatigue: 30,
    status: 'assigned',
    createdTurn: 4,
    tags: [],
    location_osid: 'op:sarajevo',
    personnel: 1800,
    corps_id: 'rbih_corps_sarajevo',
  },
];

/** Corps id → display name for mock OOB */
export const mockCorpsNames: Record<string, string> = {
  rs_corps_north: 'Northern Corps',
  rs_corps_east: 'Eastern Corps',
  rbih_corps_sarajevo: 'Sarajevo Corps',
};
