#!/usr/bin/env node
/**
 * Derive max_brigades_per_mun from 1991 census (organic rule).
 * Canon: roughly one brigade per municipality; sometimes more for large population
 * centers or mixed ethnicity (e.g. Sarajevo, Mostar, Travnik, Žepče).
 *
 * Rule: 2 brigades if (total population >= POP_THRESHOLD) OR (no ethnicity >= MIXED_MAJORITY).
 * Output: src/state/max_brigades_per_mun_data.ts (deterministic key order).
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const POP_THRESHOLD = 60_000;
const MIXED_MAJORITY = 0.55;

interface Breakdown {
  total: number;
  bosniak: number;
  serb: number;
  croat: number;
  other: number;
}

interface MunPop {
  total: number;
  breakdown: Breakdown;
}

interface PopulationByMun1990 {
  by_mun1990_id: Record<string, MunPop>;
}

function main(): void {
  const repoRoot = process.cwd();
  const popPath = resolve(repoRoot, 'data/derived/municipality_population_1991.json');
  const outPath = resolve(repoRoot, 'src/state/max_brigades_per_mun_data.ts');

  const raw = JSON.parse(readFileSync(popPath, 'utf8')) as PopulationByMun1990;
  const byMun = raw.by_mun1990_id ?? {};
  const overrides: Record<string, number> = {};

  for (const [mun1990_id, entry] of Object.entries(byMun)) {
    if (!entry?.breakdown?.total) continue;
    const total = entry.total;
    const b = entry.breakdown;
    const maxShare = Math.max(
      b.bosniak / total,
      b.serb / total,
      b.croat / total,
      b.other / total
    );
    const large = total >= POP_THRESHOLD;
    const mixed = maxShare < MIXED_MAJORITY;
    if (large || mixed) overrides[mun1990_id] = 2;
  }

  const keys = Object.keys(overrides).sort((a, b) => a.localeCompare(b));
  const lines = [
    '/**',
    ' * Max brigades per municipality (2 where organic rule applies, else 1).',
    ' * Generated by tools/formation/derive_max_brigades_per_mun.ts from 1991 census.',
    ' * Rule: 2 if population >= 60k OR no ethnicity >= 55% (large/mixed).',
    ' */',
    '',
    'export const MAX_BRIGADES_OVERRIDE: Record<string, number> = {'
  ];
  for (const k of keys) {
    lines.push(`  ${JSON.stringify(k)}: ${overrides[k]},`);
  }
  lines.push('};');
  lines.push('');

  writeFileSync(outPath, lines.join('\n'), 'utf8');
  console.log(`Wrote ${outPath} (${keys.length} municipalities with 2 brigades)`);
}

main();
