const { mkdirSync, readdirSync, readFileSync, writeFileSync } = require('node:fs');
const { dirname, join, relative, resolve } = require('node:path');

const ROOT = resolve(__dirname, '..', '..');
const OUTPUT = resolve(ROOT, 'docs/40_reports/working/SARAJEVO_CONSTANT_INVENTORY.md');
const SCAN_ROOTS = [resolve(ROOT, 'src/sim'), resolve(ROOT, 'src/state')];

function walk(dir) {
  const entries = readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
  const out = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.isFile() && entry.name.endsWith('.ts')) out.push(full);
  }
  return out;
}

function labelFor(name) {
  if (name === 'DEFAULT_SARAJEVO_RBIH_EXHAUSTION_PER_TURN') return 'RBiH Sarajevo siege exhaustion';
  if (name === 'DEFAULT_SARAJEVO_RS_EXHAUSTION_PER_TURN') return 'RS Sarajevo siege exhaustion';
  return name;
}

function migrationScope(name, label) {
  const target = new Set([
    'DEFAULT_SARAJEVO_DEFENSE_BONUS',
    'DEFAULT_SARAJEVO_ATTACKER_CASUALTY_MULT',
    'DEFAULT_SARAJEVO_RBIH_EXHAUSTION_PER_TURN',
    'DEFAULT_SARAJEVO_RS_EXHAUSTION_PER_TURN',
    'DEFAULT_SARAJEVO_INTEGRITY_FLOOR',
  ]);
  return target.has(name) || label.includes('Sarajevo siege exhaustion')
    ? 'target scalar override'
    : 'out of scope / inventory only';
}

const rows = [];
const declarationPattern = /\b(?:export\s+)?const\s+([A-Za-z0-9_]*[Ss][Aa][Rr][Aa][Jj][Ee][Vv][Oo][A-Za-z0-9_]*)\s*=\s*([-+]?\d+(?:\.\d+)?)/g;

for (const file of SCAN_ROOTS.flatMap(walk).sort((a, b) => a.localeCompare(b))) {
  const rel = relative(ROOT, file).replaceAll('\\', '/');
  const lines = readFileSync(file, 'utf8').split(/\r?\n/);
  for (let i = 0; i < lines.length; i += 1) {
    declarationPattern.lastIndex = 0;
    let match;
    while ((match = declarationPattern.exec(lines[i])) !== null) {
      const name = match[1];
      const label = labelFor(name);
      rows.push({
        file: rel,
        line: i + 1,
        label,
        value: match[2],
        sourceTier: 'no source',
        migrationScope: migrationScope(name, label),
      });
    }
  }
}

rows.sort((a, b) => {
  const fc = a.file.localeCompare(b.file);
  if (fc !== 0) return fc;
  return a.line - b.line;
});

const lines = [
  '# Sarajevo Constant Inventory',
  '',
  'Generated by `tools/diagnostics/sarajevo_constant_inventory.cjs`.',
  '',
  '| file:line | constant | current value | source-tier | migration scope |',
  '| --- | --- | ---: | --- | --- |',
  ...rows.map((row) => `| ${row.file}:${row.line} | ${row.label} | ${row.value} | ${row.sourceTier} | ${row.migrationScope} |`),
  '',
];

mkdirSync(dirname(OUTPUT), { recursive: true });
writeFileSync(OUTPUT, lines.join('\n'), 'utf8');
process.stdout.write(`sarajevo constant inventory: ${rows.length} entries\n`);
