#!/usr/bin/env node
/**
 * Find tests that assert "this must NOT appear" against un-stripped source text.
 *
 * WHY THIS EXISTS, AND WHY THE PREVIOUS FIX DID NOT WORK.
 *
 * A negative assertion over a source file reads PROSE AS CODE, and the prose most likely to mention
 * a banned construct is the comment explaining why it is banned. It has now fired FOUR times in two
 * sessions, every time on the file's own explanation:
 *
 *   - `not.toMatch(/--font-command:[^;]*Caveat/)`   matched the CSS comment saying the marker font
 *                                                   must not be routed through --font-command
 *   - `not.toMatch(/Math\.random\(/)`               matched the doc comment saying a Math.random()
 *                                                   here would break determinism
 *   - `not.toMatch(/padding.*%/)`                   matched the comment recording why the % padding
 *                                                   was removed
 *   - `not.toContain('viewBox="0 0 100 100"')`      matched the comment recording why the square
 *                                                   viewBox was removed
 *
 * After the first, `tests/helpers/sourceComments.ts` was written to own the stripping. It did not
 * stop the next three, because a helper only helps if you remember to call it — that is a rule
 * written down, which is the weakest tier there is. This scanner moves the same rule to a tier where
 * forgetting is caught: CI fails on a NEW test with the shape.
 *
 * BASELINED, not retro-fixed. 190 existing test files match, and most are almost certainly fine —
 * rewriting them blind would be a large diff with no measured defect behind it. The baseline records
 * what exists; the test forbids growth.
 *
 * Usage:
 *   node tools/scan_negative_source_assertions.cjs            list offenders not in the baseline
 *   node tools/scan_negative_source_assertions.cjs --update   rewrite the baseline
 */

'use strict';

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const TEST_ROOT = 'tests';
const BASELINE = 'tests/negative_source_assertion_baseline.json';
const HELPERS = ['withoutComments', 'withoutBlockComments', 'withoutLineComments'];

function strictCompare(a, b) {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
}

function testFiles(repoRoot = REPO_ROOT) {
  const found = [];
  const visit = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) visit(full);
      else if (/\.test\.[cm]?tsx?$/.test(entry.name)) {
        found.push(path.relative(repoRoot, full).replaceAll('\\', '/'));
      }
    }
  };
  visit(path.join(repoRoot, TEST_ROOT));
  return found.sort(strictCompare);
}

/**
 * Does this file read source text and then assert something is absent from it, without stripping?
 *
 * Deliberately crude. It cannot tell which string a negative assertion applies to, so it asks the
 * cheaper question: does the file read a file AND make a negative text assertion AND never strip
 * comments. That over-reports, which is why the answer is a baseline rather than a hard ban.
 */
function offends(relPath, repoRoot = REPO_ROOT) {
  const source = fs.readFileSync(path.join(repoRoot, relPath), 'utf8');
  const readsSource = /readFileSync\s*\([^)]*['"]utf8['"]\s*\)/.test(source);
  if (!readsSource) return false;
  const assertsAbsence = /\.not\s*\.\s*(?:toContain|toMatch)\s*\(/.test(source);
  if (!assertsAbsence) return false;
  return !HELPERS.some((helper) => source.includes(helper));
}

function scan(repoRoot = REPO_ROOT) {
  return testFiles(repoRoot).filter((file) => offends(file, repoRoot));
}

function loadBaseline(repoRoot = REPO_ROOT) {
  const full = path.join(repoRoot, BASELINE);
  if (!fs.existsSync(full)) return [];
  return JSON.parse(fs.readFileSync(full, 'utf8')).files ?? [];
}

function main() {
  const update = process.argv.slice(2).includes('--update');
  const offenders = scan();

  if (update) {
    fs.writeFileSync(
      path.join(REPO_ROOT, BASELINE),
      `${JSON.stringify({
        $comment: [
          'Test files that assert absence against un-stripped source text.',
          'GENERATED by tools/scan_negative_source_assertions.cjs --update.',
          'This list may SHRINK freely. It must not grow: a new entry means a new test that can',
          'match its own explanatory comment instead of the code it is checking.',
          'Fix by stripping first — see tests/helpers/sourceComments.ts.',
        ],
        files: offenders,
      }, null, 2)}\n`,
    );
    console.log(`baseline updated: ${offenders.length} file(s)`);
    process.exit(0);
  }

  const baseline = new Set(loadBaseline());
  const added = offenders.filter((file) => !baseline.has(file));
  if (added.length > 0) {
    console.error(`${added.length} NEW test file(s) assert absence against un-stripped source:`);
    for (const file of added) console.error(`  - ${file}`);
    console.error('\nStrip comments first (tests/helpers/sourceComments.ts). A "must NOT appear"');
    console.error('check reads prose as code, and the comment explaining a ban is the prose most');
    console.error('likely to mention it. This has already happened four times.');
    process.exit(1);
  }

  const removed = [...baseline].filter((file) => !offenders.includes(file));
  console.log(`negative-assertion hygiene: OK — ${offenders.length} baselined`
    + (removed.length > 0 ? `, ${removed.length} since fixed (run --update to shrink)` : ''));
  process.exit(0);
}

if (require.main === module) main();

module.exports = { scan, offends, loadBaseline, BASELINE };
